import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { Context } from "@deepseek-ai/cordis";
import LlmRuntime, { LlmAdapter } from "@deepseek-ai/dsh-llm";
import SessionStore, { SessionId } from "@deepseek-ai/dsh-session";
import SystemPrompt from "@deepseek-ai/dsh-system-prompt";
import ToolRuntime from "@deepseek-ai/dsh-tools";
import AgentRegistry from "@deepseek-ai/dsh-agent";
import AgentLoop from "@deepseek-ai/dsh-agent-loop";
import { buildGraph } from "../src/graph.ts";
import { ExplainScheduler, MAX_EXPLAIN_PROMPT_BYTES, processConfirmedJob } from "../src/explain-scheduler.ts";
import { assertReferenceTarget, computeGraphDigest, createJobRecord, finalizeExplain, jobRecordPath, listFolderEntries, listReferenceEntries, markRunningJobsInterrupted, prepareExplain, readFolderText, readJobRecord, readReferenceText, setExplainFinalizeFailpoint, setExplainWriteFailpoint, updateJobRecord } from "../src/explain-artifacts.ts";
import { runPrepare } from "../src/explain-native.ts";
import { readValidatedExplainFinal } from "@icomposer/workbench-contracts/ici-explain";

function toolCall(id: string, name: string, args: unknown): any[] { const text = JSON.stringify(args); return [{ type: "block-start", index: 0, blockType: "tool-call" }, { type: "tool-call-delta", index: 0, id, name, argumentsDelta: text }, { type: "block-end", index: 0, block: { type: "tool-call", id, name, arguments: text } }, { type: "finish", reason: { kind: "tool-calls" } }]; }
async function fixture() {
  const root = await mkdtemp(join(tmpdir(), "task051-mvp-")); await mkdir(join(root, "src"), { recursive: true }); await mkdir(join(root, "ref_doc", "nested"), { recursive: true });
  await writeFile(join(root, "src", "MvpAPI.groovy"), "class MvpAPI {\n  def execute() { return 1 }\n}\n"); await writeFile(join(root, "ref_doc", "nested", "meaning.md"), "business meaning\n"); await writeFile(join(root, "ref_doc", "binary.pdf"), "not selected\n");
  const raw = await buildGraph(root, [{ name: "MvpAPI", type: "api", sourcePath: join(root, "src", "MvpAPI.groovy") }]); const graph: any = { nodes: new Map(raw.nodes.map(node => [node.id, node])), edges: raw.edges, manifest: { sourceFingerprint: "f".repeat(64) } };
  await mkdir(join(root, ".metadata/icomposer/ici/graph/current"), { recursive: true }); await writeFile(join(root, ".metadata/icomposer/ici/graph/current/manifest.json"), JSON.stringify({ engineVersion: "0.2.0", sourceFingerprint: graph.manifest.sourceFingerprint, graphDigest: computeGraphDigest(graph) }));
  const start = raw.nodes.find(node => node.id === "api:MvpAPI")!; const prepared = await prepareExplain(root, "mvp", graph, start, []); const job = await createJobRecord(root, { jobId: "0123456789abcdef", workspaceId: "mvp", apiName: "MvpAPI", apiId: "api:MvpAPI", prepareArtifactPath: prepared.artifactPath, contextHash: prepared.artifact.contextHash, prepareId: prepared.artifact.prepareId, sourceFingerprint: prepared.artifact.manifest.sourceFingerprint, graphDigest: prepared.artifact.manifest.graphDigest, provider: "mvp", model: "mvp-model", docs: [], folderPath: "ref_doc" });
  return { root, graph, prepared, job, cleanup: () => rm(root, { recursive: true, force: true }) };
}
class ScriptedAdapter extends LlmAdapter {
  readonly requests: any[] = []; calls = 0;
  override resolveModel(provider: string, model: string): Promise<any> { return Promise.resolve({ provider, id: model, name: model }); }
  override listModels(provider: string): Promise<any[]> { return Promise.resolve([{ provider, id: "mvp-model", name: "MVP model" }]); }
  async *stream(options: any): AsyncIterable<any> { this.requests.push(options); const call = this.calls++; if (call === 0) yield* toolCall("list", "ici_explain_list", {}); else if (call === 1) yield* toolCall("read", "ici_explain_read", { path: "nested/meaning.md" }); else yield* toolCall("submit", "ici_explain_submit", { technical: "technical", business: "business", flow: ["API reads a request"], evidence: ["ref_doc/nested/meaning.md#1"] }); }
}

async function realHarness(adapter: ScriptedAdapter) {
  const ctx: any = new Context(); await ctx.plugin(LlmRuntime); await ctx.plugin(SessionStore); await ctx.plugin(SystemPrompt); await ctx.plugin(ToolRuntime); await ctx.plugin(AgentRegistry); await ctx.plugin(AgentLoop, { agents: [] }); ctx.llm.registerAdapter(["mvp"], adapter); return ctx;
}

test("TASK-051 MVP real AgentLoop child exposes only list/read/submit and publishes final", async () => {
  const fx = await fixture(); const adapter = new ScriptedAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root });
  try {
    await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); const before = parent.session.events.length; await processConfirmedJob(ctx.llm, fx.root, fx.job.jobId, new AbortController().signal, ctx, parent);
    assert.equal((await readJobRecord(fx.root, fx.job.jobId))?.status, "final"); assert.equal(adapter.calls, 3); assert.equal(parent.options.model, "mvp-model"); assert.equal(parent.session.events.length, before); assert.equal(ctx.agents.list().length, 1);
    assert.deepEqual(adapter.requests.map(request => request.tools?.map((tool: any) => tool.name)), [["ici_explain_list", "ici_explain_read", "ici_explain_submit"], ["ici_explain_list", "ici_explain_read", "ici_explain_submit"], ["ici_explain_list", "ici_explain_read", "ici_explain_submit"]]); assert.ok(adapter.requests.every(request => request.provider === "mvp" && request.model === "mvp-model" && Buffer.byteLength(JSON.stringify({ provider: request.provider, model: request.model, system: request.system, messages: request.messages, tools: request.tools }), "utf8") <= MAX_EXPLAIN_PROMPT_BYTES));
    assert.ok(JSON.stringify(adapter.requests[0].messages[0]?.content ?? "").includes("MvpAPI")); assert.ok(await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp"));
  } finally { parent.cancel("cancelled"); await ctx.agents.get(parent.id)?.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP folder browser and reader enforce relative containment, extensions, and limits", async () => {
  const fx = await fixture();
  try {
    await writeFile(join(fx.root, "ref_doc", "unsupported.xml"), "xml"); await writeFile(join(fx.root, "ref_doc", "unsupported.properties"), "properties"); await writeFile(join(fx.root, "root.md"), "root text\n"); const entries = await listFolderEntries(fx.root, "ref_doc"); assert.ok(entries.some(entry => entry.path === "ref_doc/nested" && entry.kind === "directory")); assert.ok(entries.some(entry => entry.path.endsWith("binary.pdf") && entry.supported === false)); assert.ok(entries.some(entry => entry.path.endsWith("unsupported.xml") && entry.supported === false)); assert.ok(entries.some(entry => entry.path.endsWith("unsupported.properties") && entry.supported === false));
    const read = await readFolderText(fx.root, "ref_doc", "nested/meaning.md"); assert.deepEqual(read.content, "business meaning\n"); assert.match(read.sha256, /^[a-f0-9]{64}$/); assert.equal((await readFolderText(fx.root, "", "root.md")).path, "root.md"); await assert.rejects(() => readFolderText(fx.root, "ref_doc", "unsupported.xml")); await assert.rejects(() => readFolderText(fx.root, "ref_doc", "unsupported.properties"));
    for (const bad of ["../", "/tmp", "ref_doc/../src", "ref_doc\\nested", "ref_doc/.", "ref_doc/\\u0000x"]) await assert.rejects(() => listFolderEntries(fx.root, bad));
    await assert.rejects(() => readFolderText(fx.root, "ref_doc", "../src/MvpAPI.groovy")); await assert.rejects(() => readFolderText(fx.root, "ref_doc", "binary.pdf"));
    await symlink(join(fx.root, "src"), join(fx.root, "ref_doc", "escape")); await assert.rejects(() => listFolderEntries(fx.root, "ref_doc/escape"));
    await writeFile(join(fx.root, "ref_doc", "large.md"), "x".repeat(64 * 1024 + 1)); await assert.rejects(() => readFolderText(fx.root, "ref_doc", "large.md"));
    const many = await mkdtemp(join(fx.root, "many-")); for (let i = 0; i < 205; i++) await writeFile(join(many, `f${i}.md`), "x"); const listed = await listFolderEntries(fx.root, many.slice(fx.root.length + 1)); assert.ok(listed.length <= 200);
  } finally { await fx.cleanup(); }
});

test("TASK-054 workspace reference targets enforce file exactness and directory descendants", async () => {
  const fx = await fixture(); const fileTarget = { path: "ref_doc/nested/meaning.md", kind: "file" as const }; const dirTarget = { path: "ref_doc", kind: "directory" as const };
  try {
    await assertReferenceTarget(fx.root, fileTarget); const fileListing = await listReferenceEntries(fx.root, fileTarget); assert.deepEqual(fileListing, [{ path: "meaning.md", kind: "file", supported: true }]); const file = await readReferenceText(fx.root, fileTarget, "meaning.md"); assert.equal(file.path, fileTarget.path); assert.equal(file.content, "business meaning\n"); await assert.rejects(() => readReferenceText(fx.root, fileTarget, "nested/meaning.md")); await assert.rejects(() => readReferenceText(fx.root, fileTarget, "other.md"));
    const nested = await listReferenceEntries(fx.root, dirTarget, "nested"); assert.ok(nested.some(entry => entry.path === "meaning.md" && entry.kind === "file")); const descendant = await readReferenceText(fx.root, dirTarget, "nested/meaning.md"); assert.equal(descendant.path, "ref_doc/nested/meaning.md"); assert.equal(descendant.content, "business meaning\n"); await assert.rejects(() => assertReferenceTarget(fx.root, { path: "ref_doc/nested/meaning.xml", kind: "file" })); await assert.rejects(() => assertReferenceTarget(fx.root, { path: "../outside", kind: "directory" }));
  } finally { await fx.cleanup(); }
});

test("TASK-051 MVP concurrent prepare is serialized per workspace", async () => {
  const fx = await fixture(); const start = fx.graph.nodes.get("api:MvpAPI"); const deps: any = { disposed: () => false, loadBase: async () => ({ ok: true, value: { graph: fx.graph, canonicalPath: fx.root, start } }), current: async () => ({ ok: true, value: { canonicalPath: fx.root, sourceFingerprint: fx.graph.manifest.sourceFingerprint, graphDigest: computeGraphDigest(fx.graph) } }), refs: async () => [] };
  try { const results = await Promise.all([runPrepare(deps, { workspaceId: "parallel", query: "MvpAPI" }), runPrepare(deps, { workspaceId: "parallel", query: "MvpAPI" })]); assert.equal(results.filter(result => result.ok).length, 1); assert.deepEqual(results.filter(result => !result.ok).map(result => result.error.code), ["job-active"]); } finally { await fx.cleanup(); }
});

test("TASK-051 MVP restart changes running to interrupted and preserves prior final on failed job", async () => {
  const fx = await fixture();
  try {
    const running = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); const active = await updateJobRecord(fx.root, fx.job.jobId, running.revision, { status: "running" }); await markRunningJobsInterrupted(fx.root); assert.equal((await readJobRecord(fx.root, fx.job.jobId))?.status, "interrupted");
    const again = await updateJobRecord(fx.root, fx.job.jobId, (await readJobRecord(fx.root, fx.job.jobId))!.revision, { status: "interrupted" }); void again;
    assert.equal(await readValidatedExplainFinal(fx.root), null);
    await assert.rejects(() => updateJobRecord(fx.root, fx.job.jobId, active.revision, { status: "final" }));
  } finally { await fx.cleanup(); }
});

test("TASK-054 file reference child reads only the selected file", async () => {
  const fx = await fixture(); class FileAdapter extends LlmAdapter { calls = 0; override resolveModel(provider: string, model: string): Promise<any> { return Promise.resolve({ provider, id: model, name: model }); } async *stream(): AsyncIterable<any> { const call = this.calls++; if (call === 0) yield* toolCall("list", "ici_explain_list", {}); else if (call === 1) yield* toolCall("read", "ici_explain_read", { path: "meaning.md" }); else yield* toolCall("submit", "ici_explain_submit", { technical: "technical", business: "business", flow: ["API reads a request"], evidence: ["ref_doc/nested/meaning.md#1"] }); } }
  const adapter = new FileAdapter(); const ctx: any = await realHarness(adapter as any); const parent = ctx.agentLoop.create(SessionId("mvp-file-target-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); const prepared = fx.prepared; const created = await createJobRecord(fx.root, { jobId: "fedcba0123456781", workspaceId: "mvp", apiName: "MvpAPI", apiId: "api:MvpAPI", prepareArtifactPath: prepared.artifactPath, contextHash: prepared.artifact.contextHash, prepareId: prepared.artifact.prepareId, sourceFingerprint: fx.job.sourceFingerprint, graphDigest: fx.job.graphDigest, provider: "mvp", model: "mvp-model", docs: [], folderPath: "ref_doc/nested/meaning.md", referenceTarget: { path: "ref_doc/nested/meaning.md", kind: "file" } });
  try { const scheduled = await updateJobRecord(fx.root, created.jobId, created.revision, { status: "scheduled", notBefore: new Date().toISOString() }); await processConfirmedJob(ctx.llm, fx.root, scheduled.jobId, new AbortController().signal, ctx, parent); assert.equal((await readJobRecord(fx.root, scheduled.jobId))?.status, "final"); assert.equal(adapter.calls, 3); assert.ok(await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp")); } finally { parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-054 persisted old-engine scheduled jobs fail closed and preserve the prior final", async () => {
  const fx = await fixture(); const adapter = new ScriptedAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-old-engine-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root });
  try {
    const analysis = { api: { technical: "technical", business: "business", flow: ["API reads a request"], evidence: ["src/MvpAPI.groovy#1"] } }; await assert.rejects(() => finalizeExplain(fx.root, "mvp", fx.prepared.artifactPath, analysis, { sourceFingerprint: fx.job.sourceFingerprint, graphDigest: fx.job.graphDigest, engineVersion: "0.1.0" }), /stale-snapshot/); const previous = await finalizeExplain(fx.root, "mvp", fx.prepared.artifactPath, analysis, { sourceFingerprint: fx.job.sourceFingerprint, graphDigest: fx.job.graphDigest, engineVersion: "0.2.0" }, undefined, "1111111111111111");
    const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); const persisted = JSON.parse(await readFile(jobRecordPath(fx.root, scheduled.jobId), "utf8")); await writeFile(jobRecordPath(fx.root, scheduled.jobId), JSON.stringify({ ...persisted, engineVersion: "0.1.0" }), "utf8"); const graphManifestPath = join(fx.root, ".metadata/icomposer/ici/graph/current/manifest.json"); const graphManifest = JSON.parse(await readFile(graphManifestPath, "utf8")); await writeFile(graphManifestPath, JSON.stringify({ ...graphManifest, engineVersion: "0.1.0" }), "utf8");
    await processConfirmedJob(ctx.llm, fx.root, scheduled.jobId, new AbortController().signal, ctx, parent); const after = await readJobRecord(fx.root, scheduled.jobId); assert.equal(after?.status, "failed"); assert.equal(after?.error, "stale-snapshot"); assert.equal(adapter.calls, 0); assert.match(await readFile(join(fx.root, previous.artifactPath), "utf8"), /MvpAPI/); const retainedState = JSON.parse(await readFile(join(fx.root, ".metadata/icomposer/ici/explain/state.json"), "utf8")); assert.equal(retainedState.artifactPath, previous.artifactPath);
  } finally { parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-054 legacy scheduled jobs without an engine version fail closed", async () => {
  const fx = await fixture(); const adapter = new ScriptedAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-legacy-engine-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root });
  try {
    const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); const persisted = JSON.parse(await readFile(jobRecordPath(fx.root, scheduled.jobId), "utf8")); delete persisted.engineVersion; await writeFile(jobRecordPath(fx.root, scheduled.jobId), JSON.stringify(persisted), "utf8"); await processConfirmedJob(ctx.llm, fx.root, scheduled.jobId, new AbortController().signal, ctx, parent); const after = await readJobRecord(fx.root, scheduled.jobId); assert.equal(after?.status, "failed"); assert.equal(after?.error, "stale-snapshot"); assert.equal(adapter.calls, 0);
  } finally { parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP scheduler keeps future jobs idle and starts once when timer is due", async () => {
  const fx = await fixture(); const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date(Date.now() + 80).toISOString() }); let children = 0; let maintenance = 0; const parent: any = { whenIdle: async () => undefined, runMaintenance: (task: any) => { maintenance++; return task(new AbortController().signal); } }; const child: any = { id: "child", followup: () => undefined, whenIdle: async () => undefined, cancel: () => undefined }; const ctx: any = new Context(); ctx.provide("agents", { roots: () => [parent], create: async () => { children++; return { agent: child, dispose: async () => undefined }; } }); ctx.provide("llm", { listProviders: () => [{ id: "mvp" }] }); ctx.provide("workspaceBinding", { list: async () => ({ ok: true, value: [{ workspaceId: "mvp", canonicalPath: fx.root }] }), get: async () => ({ ok: true, value: { canonicalPath: fx.root } }) }); const fiber: any = await ctx.plugin(ExplainScheduler); await fiber.await();
  try { await new Promise(resolve => setTimeout(resolve, 20)); assert.equal(children, 0); await updateJobRecord(fx.root, fx.job.jobId, scheduled.revision, { status: "scheduled", notBefore: new Date().toISOString() }); await new Promise(resolve => setTimeout(resolve, 80)); assert.equal(children, 1); assert.ok(maintenance >= 1); } finally { await fiber.dispose(); await fx.cleanup(); }
});

test("TASK-051 MVP scheduler launches the child from idle without holding the parent turn", async () => {
  const fx = await fixture(); const adapter = new ScriptedAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-scheduler-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); void scheduled; ctx.provide("workspaceBinding", { list: async () => ({ ok: true, value: [{ workspaceId: "mvp", canonicalPath: fx.root }] }), get: async () => ({ ok: true, value: { canonicalPath: fx.root } }) }); const fiber: any = await ctx.plugin(ExplainScheduler); await fiber.await();
  try { for (let i = 0; i < 100 && (await readJobRecord(fx.root, fx.job.jobId))?.status !== "final"; i++) await new Promise(resolve => setTimeout(resolve, 5)); assert.equal((await readJobRecord(fx.root, fx.job.jobId))?.status, "final"); assert.equal(adapter.calls, 3); assert.equal(parent.session.events.filter((event: any) => event.type === "agent/inbox/spliced").length, 0); } finally { await fiber.dispose(); parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP child without submit or after a bounded read cannot publish a final", async () => {
  const fx = await fixture(); await writeFile(join(fx.root, "ref_doc", "large.md"), "x".repeat(64 * 1024 + 1));
  class NoSubmitAdapter extends LlmAdapter { override resolveModel(provider: string, model: string): Promise<any> { return Promise.resolve({ provider, id: model, name: model }); } async *stream(): AsyncIterable<any> { yield { type: "block-start", index: 0, blockType: "text" }; yield { type: "text-delta", index: 0, text: "no submit" }; yield { type: "finish", reason: { kind: "stop" } }; } }
  class OversizeAdapter extends LlmAdapter { calls = 0; override resolveModel(provider: string, model: string): Promise<any> { return Promise.resolve({ provider, id: model, name: model }); } async *stream(): AsyncIterable<any> { const call = this.calls++; if (call === 0) yield* toolCall("list", "ici_explain_list", {}); else yield* toolCall(`read-${call}`, call === 1 ? "ici_explain_read" : "ici_explain_submit", call === 1 ? { path: "large.md" } : { technical: "t", business: "b", flow: [], evidence: ["ref_doc/large.md#1"] }); } }
  for (const Adapter of [NoSubmitAdapter, OversizeAdapter]) { const adapter = new Adapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId(`mvp-parent-${adapter.constructor.name}`), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); const current = await readJobRecord(fx.root, fx.job.jobId); const prepared = current?.status === "awaiting-input" ? undefined : await prepareExplain(fx.root, "mvp", fx.graph, fx.graph.nodes.get("api:MvpAPI"), []); const target = current?.status === "awaiting-input" ? fx.job : await createJobRecord(fx.root, { jobId: "fedcba0123456789", workspaceId: "mvp", apiName: "MvpAPI", apiId: "api:MvpAPI", prepareArtifactPath: prepared!.artifactPath, contextHash: prepared!.artifact.contextHash, prepareId: prepared!.artifact.prepareId, sourceFingerprint: prepared!.artifact.manifest.sourceFingerprint, graphDigest: prepared!.artifact.manifest.graphDigest, provider: "mvp", model: "mvp-model", docs: [], folderPath: "ref_doc" }); const confirmed = target.status === "awaiting-input" ? await updateJobRecord(fx.root, target.jobId, target.revision, { status: "scheduled", notBefore: new Date().toISOString() }) : target;
    try { await processConfirmedJob(ctx.llm, fx.root, confirmed.jobId, new AbortController().signal, ctx, parent); assert.equal((await readJobRecord(fx.root, confirmed.jobId))?.status, "failed"); assert.equal(await readValidatedExplainFinal(fx.root, undefined, "mvp"), null); assert.equal(ctx.agents.list().length, 1); } finally { parent.cancel("cancelled"); await parent.whenIdle(); }
  }
  await fx.cleanup();
});

test("TASK-051 MVP scheduled timer re-arms after restart and offline roots wait", async () => {
  const fx = await fixture(); const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date(Date.now() + 70).toISOString() }); let children = 0; const child: any = { id: "child", followup: () => undefined, whenIdle: async () => undefined, cancel: () => undefined }; const parent: any = { id: "parent", whenIdle: async () => undefined, runMaintenance: (task: any) => task(new AbortController().signal) }; const make = async (roots: any[]) => { const ctx: any = new Context(); ctx.provide("llm", { listProviders: () => [{ id: "mvp" }] }); ctx.provide("workspaceBinding", { list: async () => ({ ok: true, value: [{ workspaceId: "mvp", canonicalPath: fx.root }] }), get: async () => ({ ok: true, value: { canonicalPath: fx.root } }) }); ctx.provide("agents", { roots: () => roots, create: async () => { children++; return { agent: child, dispose: async () => undefined }; } }); const fiber: any = await ctx.plugin(ExplainScheduler); await fiber.await(); return { ctx, fiber }; };
  const first = await make([]); await first.fiber.dispose(); const roots: any[] = [parent]; const second = await make(roots); try { await new Promise(resolve => setTimeout(resolve, 20)); assert.equal(children, 0); await new Promise(resolve => setTimeout(resolve, 100)); assert.equal(children, 1); assert.equal((await readJobRecord(fx.root, scheduled.jobId))?.status, "failed"); } finally { await second.fiber.dispose(); await fx.cleanup(); }
});

test("TASK-051 MVP malformed child stream cannot complete without an exact terminal finish", async () => {
  const fx = await fixture(); class MalformedAdapter extends LlmAdapter { override resolveModel(provider: string, model: string): Promise<any> { return Promise.resolve({ provider, id: model, name: model }); } async *stream(): AsyncIterable<any> { yield { type: "text-delta", index: 0, text: "partial" }; } }
  const ctx: any = await realHarness(new MalformedAdapter()); const parent = ctx.agentLoop.create(SessionId("mvp-malformed-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); try { const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); await processConfirmedJob(ctx.llm, fx.root, scheduled.jobId, new AbortController().signal, ctx, parent); assert.equal((await readJobRecord(fx.root, scheduled.jobId))?.status, "failed"); assert.equal(await readValidatedExplainFinal(fx.root, undefined, "mvp"), null); } finally { parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP failed retry preserves the previous valid final", async () => {
  const fx = await fixture(); const adapter = new ScriptedAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-preserve-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root });
  try {
    const first = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); await processConfirmedJob(ctx.llm, fx.root, first.jobId, new AbortController().signal, ctx, parent); const previous = await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp"); assert.ok(previous);
    class FailureAdapter extends LlmAdapter { override resolveModel(provider: string, model: string): Promise<any> { return Promise.resolve({ provider, id: model, name: model }); } async *stream(): AsyncIterable<any> { yield { type: "finish", reason: { kind: "stop" } }; } }
    const p = await prepareExplain(fx.root, "mvp", fx.graph, fx.graph.nodes.get("api:MvpAPI"), []); const next = await createJobRecord(fx.root, { jobId: "fedcba9876543210", workspaceId: "mvp", apiName: "MvpAPI", apiId: "api:MvpAPI", prepareArtifactPath: p.artifactPath, contextHash: p.artifact.contextHash, prepareId: p.artifact.prepareId, sourceFingerprint: p.artifact.manifest.sourceFingerprint, graphDigest: p.artifact.manifest.graphDigest, provider: "mvp", model: "mvp-model", docs: [], folderPath: "ref_doc" }); const scheduled = await updateJobRecord(fx.root, next.jobId, next.revision, { status: "scheduled", notBefore: new Date().toISOString() }); const failureCtx: any = await realHarness(new FailureAdapter()); const failureParent = failureCtx.agentLoop.create(SessionId("mvp-failure-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); try { await processConfirmedJob(failureCtx.llm, fx.root, scheduled.jobId, new AbortController().signal, failureCtx, failureParent); assert.equal((await readJobRecord(fx.root, scheduled.jobId))?.status, "failed"); assert.equal((await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp"))?.artifactPath, previous!.artifactPath); } finally { failureParent.cancel("cancelled"); await failureParent.whenIdle(); }
  } finally { parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP submit re-hashes folder reads and rejects a changed file", async () => {
  const fx = await fixture(); class MutatingAdapter extends LlmAdapter { override resolveModel(provider: string, model: string): Promise<any> { return Promise.resolve({ provider, id: model, name: model }); } calls = 0; async *stream(): AsyncIterable<any> { const call = this.calls++; if (call === 0) yield* toolCall("list", "ici_explain_list", {}); else if (call === 1) yield* toolCall("read", "ici_explain_read", { path: "nested/meaning.md" }); else { await writeFile(join(fx.root, "ref_doc", "nested", "meaning.md"), "mutated\n"); yield* toolCall("submit", "ici_explain_submit", { technical: "technical", business: "business", flow: ["API reads a request"], evidence: ["ref_doc/nested/meaning.md#1"] }); } } }
  const adapter = new MutatingAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-folder-change-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); try { const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); await processConfirmedJob(ctx.llm, fx.root, scheduled.jobId, new AbortController().signal, ctx, parent); assert.equal((await readJobRecord(fx.root, fx.job.jobId))?.status, "failed"); assert.equal((await readJobRecord(fx.root, fx.job.jobId))?.error, "folder-changed"); assert.equal(await readValidatedExplainFinal(fx.root, undefined, "mvp"), null); } finally { parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP child request envelope remains bounded across tool history", async () => {
  const fx = await fixture(); for (let i = 1; i <= 4; i++) await writeFile(join(fx.root, "ref_doc", `history-${i}.md`), "x".repeat(63 * 1024)); class HistoryAdapter extends LlmAdapter { readonly requests: any[] = []; calls = 0; override resolveModel(provider: string, model: string): Promise<any> { return Promise.resolve({ provider, id: model, name: model }); } async *stream(options: any): AsyncIterable<any> { this.requests.push(options); const call = this.calls++; if (call === 0) yield* toolCall("list", "ici_explain_list", {}); else if (call <= 4) yield* toolCall(`read-${call}`, "ici_explain_read", { path: `history-${call}.md` }); else yield* toolCall("submit", "ici_explain_submit", { technical: "technical", business: "business", flow: ["bounded"], evidence: ["ref_doc/history-1.md#1"] }); } }
  const adapter = new HistoryAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-history-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); try { const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); await processConfirmedJob(ctx.llm, fx.root, scheduled.jobId, new AbortController().signal, ctx, parent); const result = await readJobRecord(fx.root, fx.job.jobId); assert.equal(result?.status, "failed"); assert.equal(result?.error, "input-too-large"); assert.equal(await readValidatedExplainFinal(fx.root, undefined, "mvp"), null); assert.ok(adapter.requests.every(request => Buffer.byteLength(JSON.stringify({ provider: request.provider, model: request.model, system: request.system, messages: request.messages, tools: request.tools }), "utf8") <= MAX_EXPLAIN_PROMPT_BYTES)); } finally { parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP after-state publication fault restores the previous readiness state", async () => {
  const fx = await fixture(); const analysis = { api: { technical: "technical", business: "business", flow: ["API reads a request"], evidence: ["src/MvpAPI.groovy#1"] } }; try { const first = await finalizeExplain(fx.root, "mvp", fx.prepared.artifactPath, analysis, { sourceFingerprint: fx.job.sourceFingerprint, graphDigest: fx.job.graphDigest, engineVersion: "0.2.0" }, undefined, "1111111111111111"); const before = await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp"); assert.equal(before?.artifactPath, first.artifactPath); setExplainFinalizeFailpoint(phase => { if (phase === "after-state") throw new Error("boom"); }); await assert.rejects(() => finalizeExplain(fx.root, "mvp", fx.prepared.artifactPath, analysis, { sourceFingerprint: fx.job.sourceFingerprint, graphDigest: fx.job.graphDigest, engineVersion: "0.2.0" }, undefined, "2222222222222222")); const after = await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp"); assert.equal(after?.artifactPath, before?.artifactPath); } finally { setExplainFinalizeFailpoint(undefined); await fx.cleanup(); }
});

test("TASK-051 MVP job publication fault restores the previous readiness state", async () => {
  const fx = await fixture(); const firstCtx: any = await realHarness(new ScriptedAdapter()); const firstParent = firstCtx.agentLoop.create(SessionId("mvp-job-fault-first"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); let secondParent: any; try { const first = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); await processConfirmedJob(firstCtx.llm, fx.root, first.jobId, new AbortController().signal, firstCtx, firstParent); const previous = await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp"); assert.ok(previous); const prepared = await prepareExplain(fx.root, "mvp", fx.graph, fx.graph.nodes.get("api:MvpAPI"), []); const next = await createJobRecord(fx.root, { jobId: "fedcba0123456789", workspaceId: "mvp", apiName: "MvpAPI", apiId: "api:MvpAPI", prepareArtifactPath: prepared.artifactPath, contextHash: prepared.artifact.contextHash, prepareId: prepared.artifact.prepareId, sourceFingerprint: prepared.artifact.manifest.sourceFingerprint, graphDigest: prepared.artifact.manifest.graphDigest, provider: "mvp", model: "mvp-model", docs: [], folderPath: "ref_doc" }); const scheduled = await updateJobRecord(fx.root, next.jobId, next.revision, { status: "scheduled", notBefore: new Date().toISOString() }); let jobWrites = 0; setExplainWriteFailpoint(path => { if (path.endsWith(`${next.jobId}/job.json`) && ++jobWrites === 3) throw new Error("job-boom"); }); const secondCtx: any = await realHarness(new ScriptedAdapter()); secondParent = secondCtx.agentLoop.create(SessionId("mvp-job-fault-second"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); await processConfirmedJob(secondCtx.llm, fx.root, scheduled.jobId, new AbortController().signal, secondCtx, secondParent); assert.equal((await readJobRecord(fx.root, scheduled.jobId))?.status, "failed"); assert.equal((await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp"))?.artifactPath, previous.artifactPath); } finally { setExplainWriteFailpoint(undefined); secondParent?.cancel("cancelled"); if (secondParent) await secondParent.whenIdle(); firstParent.cancel("cancelled"); await firstParent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP publication transaction serializes cancel after final/state", async () => {
  const fx = await fixture(); const adapter = new ScriptedAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-publication-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); ctx.provide("workspaceBinding", { list: async () => ({ ok: true, value: [{ workspaceId: "mvp", canonicalPath: fx.root }] }), get: async () => ({ ok: true, value: { canonicalPath: fx.root } }) }); const scheduler: any = new ExplainScheduler(ctx); const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); let release!: () => void; let entered!: () => void; const barrier = new Promise<void>(resolve => { release = resolve; }); const reached = new Promise<void>(resolve => { entered = resolve; }); const phases: string[] = []; setExplainFinalizeFailpoint(async phase => { phases.push(phase); if (phase === "after-final") { entered(); await barrier; } }); const running = processConfirmedJob(ctx.llm, fx.root, scheduled.jobId, new AbortController().signal, ctx, parent); try { await reached; let cancelDone = false; const cancel = scheduler.cancelJob(scheduled.jobId).then(value => { cancelDone = true; return value; }); await new Promise(resolve => setTimeout(resolve, 20)); assert.equal(cancelDone, false); assert.equal((await readJobRecord(fx.root, fx.job.jobId))?.status, "running"); release(); assert.equal(await cancel, false); await running; assert.equal((await readJobRecord(fx.root, fx.job.jobId))?.status, "final"); assert.deepEqual(phases, ["before-final", "after-final", "after-state"]); assert.ok(await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp")); } finally { release(); setExplainFinalizeFailpoint(undefined); parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP dispose during finalization leaves the publication transaction consistent", async () => {
  const fx = await fixture(); const adapter = new ScriptedAdapter(); const ctx: any = await realHarness(adapter); const parent = ctx.agentLoop.create(SessionId("mvp-dispose-publication-parent"), { provider: "mvp", model: "mvp-model" }, { cwd: fx.root }); ctx.provide("workspaceBinding", { list: async () => ({ ok: true, value: [{ workspaceId: "mvp", canonicalPath: fx.root }] }), get: async () => ({ ok: true, value: { canonicalPath: fx.root } }) }); const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); let release!: () => void; let entered!: () => void; const barrier = new Promise<void>(resolve => { release = resolve; }); const reached = new Promise<void>(resolve => { entered = resolve; }); setExplainFinalizeFailpoint(async phase => { if (phase === "after-final") { entered(); await barrier; } }); const fiber: any = await ctx.plugin(ExplainScheduler); await fiber.await(); try { await reached; const disposing = fiber.dispose(); release(); await disposing; for (let i = 0; i < 100 && (await readJobRecord(fx.root, scheduled.jobId))?.status === "running"; i++) await new Promise(resolve => setTimeout(resolve, 5)); assert.equal((await readJobRecord(fx.root, scheduled.jobId))?.status, "final"); assert.ok(await readValidatedExplainFinal(fx.root, "MvpAPI", "mvp")); } finally { release(); setExplainFinalizeFailpoint(undefined); parent.cancel("cancelled"); await parent.whenIdle(); await fx.cleanup(); }
});

test("TASK-051 MVP cancel aborts the dedicated child and leaves no final", async () => {
  const fx = await fixture(); const scheduled = await updateJobRecord(fx.root, fx.job.jobId, fx.job.revision, { status: "scheduled", notBefore: new Date().toISOString() }); let created = 0; let followups = 0; let cancelled = 0; let resolveIdle: (() => void) | undefined; const child: any = { id: "child", followup: () => { followups++; }, whenIdle: () => new Promise<void>(resolve => { resolveIdle = resolve; }), cancel: () => { cancelled++; resolveIdle?.(); } }; const ctx: any = new Context(); const parent: any = { id: "parent", whenIdle: async () => undefined, runMaintenance: (task: any) => task(new AbortController().signal) }; ctx.provide("agents", { roots: () => [parent], create: async () => { created++; return { agent: child, dispose: async () => undefined }; } }); ctx.provide("llm", { listProviders: () => [{ id: "mvp" }] }); ctx.provide("workspaceBinding", { list: async () => ({ ok: true, value: [{ workspaceId: "mvp", canonicalPath: fx.root }] }), get: async () => ({ ok: true, value: { canonicalPath: fx.root } }) }); const fiber: any = await ctx.plugin(ExplainScheduler); await fiber.await();
  try { for (let i = 0; i < 40 && created === 0; i++) await new Promise(resolve => setTimeout(resolve, 5)); assert.equal(created, 1); const scheduler: any = ctx.get("iciExplainScheduler"); assert.equal(await scheduler.cancelJob(fx.job.jobId), true); for (let i = 0; i < 40 && (await readJobRecord(fx.root, fx.job.jobId))?.status !== "cancelled"; i++) await new Promise(resolve => setTimeout(resolve, 5)); assert.equal((await readJobRecord(fx.root, fx.job.jobId))?.status, "cancelled"); assert.equal(followups, 1); assert.ok(cancelled >= 1); await new Promise(resolve => setTimeout(resolve, 30)); } finally { await fiber.dispose(); await new Promise(resolve => setTimeout(resolve, 100)); await fx.cleanup(); }
});
