import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { Context } from "@deepseek-ai/cordis";
import { buildGraph } from "../src/graph.ts";
import { ExplainRoutesService, type NativeFilePicker } from "../src/explain-routes.ts";
import { computeGraphDigest, createJobRecord, prepareExplain, readBatchRecord, readJobRecord, setExplainWriteFailpoint, updateJobRecord, writeBatchRecord } from "../src/explain-artifacts.ts";
import { ICI_ENGINE_VERSION } from "../src/engine-version.ts";

const batchId = "fedcba9876543210"; const alphaId = "0123456789abcdef"; const betaId = "abcdef0123456789";
async function fixture() {
  const root = await mkdtemp(join(tmpdir(), "task056-batch-route-")); await mkdir(join(root, "src"), { recursive: true }); await mkdir(join(root, "ref_doc"), { recursive: true }); await writeFile(join(root, "src", "AlphaAPI.groovy"), "class AlphaAPI { def run() { 1 } }\n"); await writeFile(join(root, "src", "BetaAPI.groovy"), "class BetaAPI { def run() { 2 } }\n"); await writeFile(join(root, "ref_doc", "guide.md"), "guide\n");
  const raw = await buildGraph(root, [{ name: "AlphaAPI", type: "api", sourcePath: join(root, "src", "AlphaAPI.groovy") }, { name: "BetaAPI", type: "api", sourcePath: join(root, "src", "BetaAPI.groovy") }]); const graph: any = { nodes: new Map(raw.nodes.map(node => [node.id, node])), edges: raw.edges, manifest: { sourceFingerprint: "f".repeat(64) } }; const graphDir = join(root, ".metadata/icomposer/ici/graph/current"); await mkdir(graphDir, { recursive: true }); await writeFile(join(graphDir, "manifest.json"), JSON.stringify({ engineVersion: ICI_ENGINE_VERSION, sourceFingerprint: graph.manifest.sourceFingerprint, graphDigest: computeGraphDigest(graph) }));
  const jobs = []; for (const [id, name] of [[alphaId, "AlphaAPI"], [betaId, "BetaAPI"]] as const) { const prepared = await prepareExplain(root, "batch", graph, raw.nodes.find(node => node.id === `api:${name}`)!, []); jobs.push(await createJobRecord(root, { jobId: id, workspaceId: "batch", apiName: name, apiId: `api:${name}`, prepareArtifactPath: prepared.artifactPath, contextHash: prepared.artifact.contextHash, prepareId: prepared.artifact.prepareId, sourceFingerprint: prepared.artifact.manifest.sourceFingerprint, graphDigest: prepared.artifact.manifest.graphDigest, provider: null, model: null, docs: [], folderPath: "ref_doc" })); }
  await writeBatchRecord(root, { schemaVersion: 1, kind: "explain-batch", batchId, workspaceId: "batch", jobIds: [alphaId, betaId], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); return { root, jobs, cleanup: () => rm(root, { recursive: true, force: true }) };
}
function req(method: string, url: string, body?: unknown, header = true): any { const bytes = body === undefined ? Buffer.alloc(0) : Buffer.from(JSON.stringify(body)); return { method, url, headers: { ...(header ? { "x-workbench-action": "1" } : {}), ...(body === undefined ? {} : { "content-type": "application/json" }), "content-length": String(bytes.byteLength) }, on: () => undefined, async *[Symbol.asyncIterator]() { if (bytes.byteLength > 0) yield bytes; } }; }
function response() { const value: any = { status: 0, body: "", headers: {}, destroyed: false, writableEnded: false, writeHead(status: number, headers: Record<string, string>) { value.status = status; value.headers = headers; }, end(body?: string) { value.body = body ?? ""; value.writableEnded = true; } }; return value; }
function decode(value: any): any { return JSON.parse(value.body); }
async function routeFixture(nativeFilePicker?: NativeFilePicker, engine?: unknown) {
  const fx = await fixture(); const routes: any[] = []; const ctx: any = new Context(); ctx.provide("webServer", { register(route: any) { routes.push(route); return () => undefined; } }); ctx.provide("workspaceBinding", { list: async () => ({ ok: true, value: [{ workspaceId: "batch", canonicalPath: fx.root }] }) }); ctx.provide("llm", { listProviders: () => [{ id: "mvp" }], resolveModelInfo: async () => undefined }); ctx.provide("iciEngine", engine ?? {}); ctx.provide("iciExplainScheduler", { poke: () => undefined, cancelJob: async (jobId: string) => { const current = await readJobRecord(fx.root, jobId); if (!current || !["awaiting-input", "scheduled", "confirmed", "running"].includes(current.status)) return false; await updateJobRecord(fx.root, jobId, current.revision, { status: "cancelled", error: "cancelled" }); return true; } }); ctx.provide("directoryPicker", { capability: () => ({ kind: "native", pick: async () => join(fx.root, "ref_doc") }) }); const fiber: any = await ctx.plugin(ExplainRoutesService, nativeFilePicker ? { nativeFilePicker } : undefined); await fiber.await(); return { fx, fiber, handler: routes[0].handler };
}
const confirmBody = { provider: "mvp", model: "mvp-model", referenceTarget: { path: "ref_doc", kind: "directory" }, docs: [], notBefore: new Date().toISOString(), consent: true };

test("TASK-056 batch status and confirm apply one safe input to every awaiting job", async () => {
  const setup = await routeFixture(); try {
    const status = response(); await setup.handler(req("GET", `/api/icomposer-workbench/ici/explain/batches/${batchId}/status`), status); const view = decode(status); assert.equal(view.ok, true); assert.equal(view.result.batch.batchId, batchId); assert.equal(view.result.jobs.length, 2); assert.equal(view.result.summary.jobCount, 2); assert.ok(view.result.jobs.every((job: any) => job.promptBaseBytes > 0)); assert.equal(status.body.includes(setup.fx.root), false);
    const confirmed = response(); await setup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/confirm`, confirmBody), confirmed); assert.equal(decode(confirmed).ok, true); assert.equal(decode(confirmed).result.applied.length, 2); assert.equal((await readJobRecord(setup.fx.root, alphaId))?.status, "scheduled"); assert.equal((await readJobRecord(setup.fx.root, betaId))?.status, "scheduled");
    const conflict = response(); await setup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/confirm`, confirmBody), conflict); assert.equal(decode(conflict).error.code, "revision-conflict");
  } finally { await setup.fiber.dispose(); await setup.fx.cleanup(); }
});

test("TASK-056 batch confirm fails before mutation when one job is stale", async () => {
  const setup = await routeFixture(); try { const first = await readJobRecord(setup.fx.root, alphaId); await rm(join(setup.fx.root, first!.prepareArtifactPath)); const result = response(); await setup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/confirm`, confirmBody), result); assert.equal(decode(result).error.code, "stale-snapshot"); assert.equal((await readJobRecord(setup.fx.root, betaId))?.status, "awaiting-input"); assert.equal(result.body.includes(setup.fx.root), false); } finally { await setup.fiber.dispose(); await setup.fx.cleanup(); }
});

test("TASK-056 batch confirm rejects mixed scheduled or failed members without partial confirmation", async () => {
  const scheduledSetup = await routeFixture(); try { const job = await readJobRecord(scheduledSetup.fx.root, betaId); await updateJobRecord(scheduledSetup.fx.root, betaId, job!.revision, { provider: "mvp", model: "mvp-model", status: "scheduled", notBefore: new Date().toISOString() }); const result = response(); await scheduledSetup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/confirm`, confirmBody), result); assert.equal(decode(result).error.code, "revision-conflict"); assert.equal((await readJobRecord(scheduledSetup.fx.root, alphaId))?.status, "awaiting-input"); assert.equal((await readJobRecord(scheduledSetup.fx.root, betaId))?.status, "scheduled"); } finally { await scheduledSetup.fiber.dispose(); await scheduledSetup.fx.cleanup(); }
  const failedSetup = await routeFixture(); try { const job = await readJobRecord(failedSetup.fx.root, betaId); await updateJobRecord(failedSetup.fx.root, betaId, job!.revision, { status: "failed", error: "model-failed" }); const result = response(); await failedSetup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/confirm`, confirmBody), result); assert.equal(decode(result).error.code, "revision-conflict"); assert.equal((await readJobRecord(failedSetup.fx.root, alphaId))?.status, "awaiting-input"); assert.equal((await readJobRecord(failedSetup.fx.root, betaId))?.status, "failed"); } finally { await failedSetup.fiber.dispose(); await failedSetup.fx.cleanup(); }
});

test("TASK-056 batch confirm rolls back earlier jobs on a later revision conflict", async () => {
  const setup = await routeFixture(); setExplainWriteFailpoint(path => { if (path.endsWith(`${betaId}/job.json`)) throw new Error("revision-conflict"); }); try { const result = response(); await setup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/confirm`, confirmBody), result); assert.equal(decode(result).error.code, "revision-conflict"); assert.equal((await readJobRecord(setup.fx.root, alphaId))?.status, "awaiting-input"); assert.equal((await readJobRecord(setup.fx.root, betaId))?.status, "awaiting-input"); } finally { setExplainWriteFailpoint(undefined); await setup.fiber.dispose(); await setup.fx.cleanup(); }
});

test("TASK-056 batch cancel and retry operate on all active or failed members", async () => {
  const cancelSetup = await routeFixture(); try { const result = response(); await cancelSetup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/cancel`, {}), result); assert.equal(decode(result).ok, true); assert.deepEqual(decode(result).result.cancelled.sort(), [alphaId, betaId].sort()); assert.equal((await readJobRecord(cancelSetup.fx.root, alphaId))?.status, "cancelled"); assert.equal((await readJobRecord(cancelSetup.fx.root, betaId))?.status, "cancelled"); } finally { await cancelSetup.fiber.dispose(); await cancelSetup.fx.cleanup(); }
  const retryId = "1111111111111111"; const retrySetup = await routeFixture(undefined, { explainPrepare: async () => ({ ok: true, value: { jobId: retryId, jobStatus: "awaiting-input", artifactPath: ".metadata/icomposer/ici/explain/AlphaAPI/prepare.json" } }) }); try { const failed = await readJobRecord(retrySetup.fx.root, alphaId); await updateJobRecord(retrySetup.fx.root, alphaId, failed!.revision, { status: "failed", error: "model-failed" }); const result = response(); await retrySetup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/retry`, {}), result); assert.equal(decode(result).ok, true); assert.deepEqual((await readBatchRecord(retrySetup.fx.root, batchId))?.jobIds, [retryId, betaId]); assert.equal(decode(result).result.retried[0].from, alphaId); } finally { await retrySetup.fiber.dispose(); await retrySetup.fx.cleanup(); }
});

test("TASK-056 batch native picker returns only a relative target and never persists it", async () => {
  const setup = await routeFixture({ pick: async () => join("/private", "outside.md") }); try {
    const directory = response(); await setup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/native-pick`, { kind: "directory" }), directory); assert.deepEqual(decode(directory).result, { path: "ref_doc", kind: "directory" }); const before = await readBatchRecord(setup.fx.root, batchId); assert.deepEqual(before?.jobIds, [alphaId, betaId]);
    const failed = response(); await setup.handler(req("POST", `/api/icomposer-workbench/ici/explain/batches/${batchId}/native-pick`, { kind: "file" }), failed); assert.equal(decode(failed).error.code, "reference-outside-workspace"); assert.equal(failed.body.includes(setup.fx.root), false); assert.equal((await readJobRecord(setup.fx.root, alphaId))?.referenceTarget?.path, "ref_doc");
  } finally { await setup.fiber.dispose(); await setup.fx.cleanup(); }
});
