import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { LocaleRuntime } from "@deepseek-ai/dsh-client-locale/client";
import { SlotTestRuntime, usePinnedBrowserLanguages } from "@deepseek-ai/dsh-client-test-runtime";
import { apply, inject } from "../src/client/index.ts";
import { zh } from "../src/client/locales.ts";

usePinnedBrowserLanguages("zh-CN");
const jobId = "0123456789abcdef";
function resultBlock() { return { kind: "tool-result" as const, call: { argsRaw: JSON.stringify({ workspace_id: "mvp", query: "MvpAPI" }) }, content: [{ type: "text", text: `prepare=.metadata/icomposer/ici/explain/MvpAPI/prepare.json job=${jobId} status=awaiting-input` }] }; }
const status = (state: string) => ({ ok: true, result: { job: { jobId, workspaceId: "mvp", apiName: "MvpAPI", provider: "mvp", model: "mvp-model", folderPath: "ref_doc", status: state, revision: 1 }, summary: { nodes: 3, edges: 2, sourceFiles: 2, readableSources: 2, sourceBytes: 1024, promptBaseBytes: 2048, truncated: false }, providers: [{ id: "mvp", models: [{ id: "mvp-model", name: "MVP model" }] }] } });

describe("TASK-051 MVP ICI toolview", () => {
  let runtime: SlotTestRuntime; let locale: LocaleRuntime; let feature: Awaited<ReturnType<SlotTestRuntime["mount"]>>;
  beforeEach(async () => { vi.stubGlobal("localStorage", { clear: () => undefined, getItem: () => null, setItem: () => undefined, removeItem: () => undefined, key: () => null, length: 0 }); runtime = await SlotTestRuntime.create(); locale = new LocaleRuntime(runtime.ctx); runtime.ctx.provide("locale", locale); runtime.slots.installLocale(locale); const owner: any = { callId: "call-1", toolName: "ici_explain", block: resultBlock() }; const Frame = ({ renderSlot }: any) => renderSlot("tool.call.toolview", owner, { entryKey: "ici_explain" }); await runtime.root.declare({ "tool.call.toolview": { kind: "keyed", scope: "root" } } as never, Frame as never); feature = await runtime.mount({ inject, apply }); });
  afterEach(async () => { await feature.dispose(); await runtime.dispose(); vi.unstubAllGlobals(); });
  it("browses nested workspace folder, sends consent/model/notBefore, and renders scheduled", async () => {
    let started = false; const fetchMock = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = String(input); if (url.endsWith(`/jobs/${jobId}/status`)) return new Response(JSON.stringify(status(started ? "scheduled" : "awaiting-input")), { status: 200 }); if (url.includes(`/jobs/${jobId}/folder`)) { const path = new URL(url, "http://localhost").searchParams.get("path"); return new Response(JSON.stringify({ ok: true, result: { folderPath: path, parentPath: path === "ref_doc/nested" ? "ref_doc" : null, entries: path === "ref_doc" ? [{ path: "ref_doc/nested", kind: "directory" }, { path: "ref_doc/readme.md", kind: "file", supported: true }] : [{ path: "ref_doc/nested/guide.md", kind: "file", supported: true }] } })); } if (url.includes(`/jobs/${jobId}/confirm`)) { started = true; const body = JSON.parse(String(init?.body)); expect(body).toMatchObject({ provider: "mvp", model: "mvp-model", referenceTarget: { path: "ref_doc/nested", kind: "directory" }, consent: true }); expect(typeof body.notBefore).toBe("string"); return new Response(JSON.stringify({ ok: true, result: { jobId, status: "scheduled", notBefore: body.notBefore, folderPath: body.folderPath } })); } return new Response(JSON.stringify({ ok: false, error: { code: "not-found", message: "not-found" } }), { status: 404 }); }); vi.stubGlobal("fetch", fetchMock);
    const view = runtime.renderRoot(); expect(await view.findByText("MvpAPI")).toBeTruthy(); expect(await view.findByText(zh["explain.folder"])).toBeTruthy(); let modelSelect!: HTMLSelectElement; await vi.waitFor(async () => { const boxes = await view.findAllByRole("combobox"); expect(boxes).toHaveLength(2); modelSelect = boxes[1] as HTMLSelectElement; expect(modelSelect.value).toBe("mvp-model"); }); expect((modelSelect.options[1] as HTMLOptionElement).textContent).toBe("MVP model · mvp-model");
    (await view.findByRole("button", { name: /nested/ })).click(); expect(await view.findByText("guide.md")).toBeTruthy(); (await view.findByRole("button", { name: zh["explain.useFolder"] })).click(); const start = await view.findByRole("button", { name: zh["explain.start"] }); start.click(); await vi.waitFor(() => expect(started).toBe(true)); expect(await view.findByText(zh["status.scheduled"])).toBeTruthy(); const confirm = fetchMock.mock.calls.find(call => String(call[0]).includes("/confirm")); expect(confirm).toBeTruthy();
  });
  it("opens an accessible workspace-only picker, supports Escape, and confirms a file target", async () => {
    let started = false; const fetchMock = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = String(input); if (url.endsWith(`/jobs/${jobId}/status`)) return new Response(JSON.stringify(status(started ? "scheduled" : "awaiting-input")), { status: 200 }); if (url.includes(`/jobs/${jobId}/folder`)) { const path = new URL(url, "http://localhost").searchParams.get("path"); return new Response(JSON.stringify({ ok: true, result: { folderPath: path, parentPath: path === "ref_doc/nested" ? "ref_doc" : null, entries: path === "ref_doc/nested" ? [{ path: "ref_doc/nested/guide.md", kind: "file", supported: true }] : [{ path: "ref_doc/nested", kind: "directory" }, { path: "ref_doc/readme.md", kind: "file", supported: true }] } })); } if (url.includes(`/jobs/${jobId}/confirm`)) { started = true; const body = JSON.parse(String(init?.body)); expect(body).toMatchObject({ provider: "mvp", model: "mvp-model", referenceTarget: { path: "ref_doc/readme.md", kind: "file" }, consent: true }); return new Response(JSON.stringify({ ok: true, result: { jobId, status: "scheduled", notBefore: body.notBefore, folderPath: body.folderPath, referenceTarget: body.referenceTarget } })); } return new Response(JSON.stringify({ ok: false, error: { code: "not-found", message: "not-found" } }), { status: 404 }); }); vi.stubGlobal("fetch", fetchMock);
    const view = runtime.renderRoot(); const open = await view.findByRole("button", { name: zh["explain.chooseReference"] }); open.click(); const dialog = await view.findByRole("dialog"); expect(dialog.getAttribute("aria-modal")).toBe("true"); expect(dialog.textContent).toContain(zh["explain.workspaceOnlyHint"]); await vi.waitFor(() => expect(document.activeElement).toBe(dialog)); dialog.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true })); await vi.waitFor(() => expect(view.queryByRole("dialog")).toBeNull()); open.click(); await view.findByRole("dialog"); (await view.findByRole("button", { name: "readme.md" })).click(); (await view.findByRole("button", { name: zh["explain.pickerConfirm"] })).click(); expect(await view.findByText("ref_doc/readme.md")).toBeTruthy(); (await view.findByRole("button", { name: zh["explain.start"] })).click(); await vi.waitFor(() => expect(started).toBe(true));
  });
});

function customResultBlock(model = "custom-model") { return { kind: "tool-result" as const, call: { argsRaw: JSON.stringify({ workspace_id: "custom", query: "CustomAPI" }) }, content: [{ type: "text", text: `prepare=.metadata/icomposer/ici/explain/CustomAPI/prepare.json job=${jobId} status=awaiting-input default=custom/${model}` }] }; }
const customStatus = (state: string, providers: readonly { id: string; models: readonly { id: string; name: string }[] }[] = [{ id: "custom", models: [] }]) => ({ ok: true, result: { job: { jobId, workspaceId: "custom", apiName: "CustomAPI", provider: null, model: null, folderPath: "ref_doc", status: state, revision: 1 }, summary: { nodes: 1, edges: 0, sourceFiles: 1, readableSources: 1, sourceBytes: 128, promptBaseBytes: 512, truncated: false }, providers } });

describe("TASK-052 custom provider model input", () => {
  let runtime: SlotTestRuntime; let locale: LocaleRuntime; let feature: Awaited<ReturnType<SlotTestRuntime["mount"]>>;
  beforeEach(async () => { vi.stubGlobal("localStorage", { clear: () => undefined, getItem: () => null, setItem: () => undefined, removeItem: () => undefined, key: () => null, length: 0 }); runtime = await SlotTestRuntime.create(); locale = new LocaleRuntime(runtime.ctx); runtime.ctx.provide("locale", locale); runtime.slots.installLocale(locale); const owner: any = { callId: "call-1", toolName: "ici_explain", block: customResultBlock() }; const Frame = ({ renderSlot }: any) => renderSlot("tool.call.toolview", owner, { entryKey: "ici_explain" }); await runtime.root.declare({ "tool.call.toolview": { kind: "keyed", scope: "root" } } as never, Frame as never); feature = await runtime.mount({ inject, apply }); });
  afterEach(async () => { await feature.dispose(); await runtime.dispose(); vi.unstubAllGlobals(); });
  it("keeps an empty catalog editable and submits the opaque model ID", async () => {
    let started = false; const fetchMock = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = String(input); if (url.endsWith(`/jobs/${jobId}/status`)) return new Response(JSON.stringify(customStatus(started ? "scheduled" : "awaiting-input")), { status: 200 }); if (url.includes(`/jobs/${jobId}/folder`)) return new Response(JSON.stringify({ ok: true, result: { folderPath: "ref_doc", parentPath: null, entries: [] } }), { status: 200 }); if (url.includes(`/jobs/${jobId}/confirm`)) { started = true; const body = JSON.parse(String(init?.body)); expect(body).toMatchObject({ provider: "custom", model: "custom-model", referenceTarget: { path: "ref_doc", kind: "directory" }, consent: true }); return new Response(JSON.stringify({ ok: true, result: { jobId, status: "scheduled", notBefore: body.notBefore, folderPath: body.folderPath } })); } return new Response(JSON.stringify({ ok: false, error: { code: "not-found", message: "not-found" } }), { status: 404 }); }); vi.stubGlobal("fetch", fetchMock);
    const view = runtime.renderRoot(); const modelInput = await view.findByDisplayValue("custom-model"); expect((modelInput as HTMLInputElement).disabled).toBe(false); (modelInput as HTMLInputElement).value = "custom-model"; modelInput.dispatchEvent(new Event("input", { bubbles: true })); (await view.findByRole("button", { name: zh["explain.start"] })).click(); await vi.waitFor(() => expect(started).toBe(true)); expect(await view.findByText(zh["status.scheduled"])).toBeTruthy(); expect(await view.findByText(zh["explain.customModelHint"])).toBeTruthy();
  });
  it("uses catalog suggestions while preserving the tool default for an empty custom catalog", async () => {
    const providers = [{ id: "custom", models: [] }, { id: "official", models: [{ id: "official-model", name: "Official model" }] }]; const fetchMock = vi.fn(async (input: RequestInfo | URL) => { const url = String(input); if (url.endsWith(`/jobs/${jobId}/status`)) return new Response(JSON.stringify(customStatus("awaiting-input", providers)), { status: 200 }); if (url.includes(`/jobs/${jobId}/folder`)) return new Response(JSON.stringify({ ok: true, result: { folderPath: "ref_doc", parentPath: null, entries: [] } }), { status: 200 }); return new Response(JSON.stringify({ ok: false, error: { code: "not-found", message: "not-found" } }), { status: 404 }); }); vi.stubGlobal("fetch", fetchMock);
    const view = runtime.renderRoot(); const modelInput = await view.findByDisplayValue("custom-model"); const providerInput = (await view.findAllByRole("combobox"))[0] as HTMLSelectElement; providerInput.value = "official"; providerInput.dispatchEvent(new Event("change", { bubbles: true })); await vi.waitFor(async () => expect((await view.findAllByRole("combobox"))[1]).toHaveProperty("value", "official-model")); expect((await view.findAllByRole("combobox"))[1].querySelector('option[value="official-model"]')?.textContent).toBe("Official model · official-model"); providerInput.value = "custom"; providerInput.dispatchEvent(new Event("change", { bubbles: true })); await vi.waitFor(async () => expect(await view.findByDisplayValue("custom-model")).toBeTruthy()); expect(await view.findByText(zh["explain.customModelHint"])).toBeTruthy();
  });
  it("prefills slash-qualified opaque model IDs from the tool result default", async () => {
    await feature.dispose(); await runtime.dispose(); vi.unstubAllGlobals(); vi.stubGlobal("localStorage", { clear: () => undefined, getItem: () => null, setItem: () => undefined, removeItem: () => undefined, key: () => null, length: 0 });
    runtime = await SlotTestRuntime.create(); locale = new LocaleRuntime(runtime.ctx); runtime.ctx.provide("locale", locale); runtime.slots.installLocale(locale); const owner: any = { callId: "call-1", toolName: "ici_explain", block: customResultBlock("org/model") }; const Frame = ({ renderSlot }: any) => renderSlot("tool.call.toolview", owner, { entryKey: "ici_explain" }); await runtime.root.declare({ "tool.call.toolview": { kind: "keyed", scope: "root" } } as never, Frame as never); feature = await runtime.mount({ inject, apply });
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => { const url = String(input); if (url.endsWith(`/jobs/${jobId}/status`)) return new Response(JSON.stringify(customStatus("awaiting-input")), { status: 200 }); if (url.includes(`/jobs/${jobId}/folder`)) return new Response(JSON.stringify({ ok: true, result: { folderPath: "ref_doc", parentPath: null, entries: [] } }), { status: 200 }); return new Response(JSON.stringify({ ok: false, error: { code: "not-found", message: "not-found" } }), { status: 404 }); }); vi.stubGlobal("fetch", fetchMock);
    const view = runtime.renderRoot(); const modelInput = await view.findByDisplayValue("org/model"); expect((modelInput as HTMLInputElement).disabled).toBe(false);
  });
});

describe("TASK-053 slash-qualified catalog models", () => {
  let runtime: SlotTestRuntime; let locale: LocaleRuntime; let feature: Awaited<ReturnType<SlotTestRuntime["mount"]>>;
  beforeEach(async () => { vi.stubGlobal("localStorage", { clear: () => undefined, getItem: () => null, setItem: () => undefined, removeItem: () => undefined, key: () => null, length: 0 }); runtime = await SlotTestRuntime.create(); locale = new LocaleRuntime(runtime.ctx); runtime.ctx.provide("locale", locale); runtime.slots.installLocale(locale); const owner: any = { callId: "call-1", toolName: "ici_explain", block: customResultBlock() }; const Frame = ({ renderSlot }: any) => renderSlot("tool.call.toolview", owner, { entryKey: "ici_explain" }); await runtime.root.declare({ "tool.call.toolview": { kind: "keyed", scope: "root" } } as never, Frame as never); feature = await runtime.mount({ inject, apply }); });
  afterEach(async () => { await feature.dispose(); await runtime.dispose(); vi.unstubAllGlobals(); });
  it("lists slash-qualified catalog ids in the select and submits the selected one", async () => {
    let started = false; const providers = [{ id: "custom", models: [{ id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" }, { id: "z-ai/glm-5.3-flash", name: "z-ai/glm-5.3-flash" }] }]; const fetchMock = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => { const url = String(input); if (url.endsWith(`/jobs/${jobId}/status`)) return new Response(JSON.stringify(customStatus(started ? "scheduled" : "awaiting-input", providers)), { status: 200 }); if (url.includes(`/jobs/${jobId}/folder`)) return new Response(JSON.stringify({ ok: true, result: { folderPath: "ref_doc", parentPath: null, entries: [] } }), { status: 200 }); if (url.includes(`/jobs/${jobId}/confirm`)) { started = true; const body = JSON.parse(String(init?.body)); expect(body).toMatchObject({ provider: "custom", model: "deepseek/deepseek-v4-flash", referenceTarget: { path: "ref_doc", kind: "directory" }, consent: true }); return new Response(JSON.stringify({ ok: true, result: { jobId, status: "scheduled", notBefore: body.notBefore, folderPath: body.folderPath } })); } return new Response(JSON.stringify({ ok: false, error: { code: "not-found", message: "not-found" } }), { status: 404 }); }); vi.stubGlobal("fetch", fetchMock);
    const view = runtime.renderRoot(); let modelSelect!: HTMLSelectElement; await vi.waitFor(async () => { const boxes = await view.findAllByRole("combobox"); expect(boxes).toHaveLength(2); modelSelect = boxes[1] as HTMLSelectElement; expect(modelSelect.value).toBe("deepseek/deepseek-v4-flash"); }); expect(modelSelect.querySelector('option[value="deepseek/deepseek-v4-flash"]')?.textContent).toBe("DeepSeek V4 Flash · deepseek/deepseek-v4-flash"); expect(modelSelect.querySelector('option[value="z-ai/glm-5.3-flash"]')?.textContent).toBe("z-ai/glm-5.3-flash · z-ai/glm-5.3-flash"); modelSelect.value = "deepseek/deepseek-v4-flash"; modelSelect.dispatchEvent(new Event("change", { bubbles: true })); (await view.findByRole("button", { name: zh["explain.start"] })).click(); await vi.waitFor(() => expect(started).toBe(true)); expect(await view.findByText(zh["status.scheduled"])).toBeTruthy(); expect(modelSelect.querySelector('option[value="deepseek/deepseek-v4-flash"]')).toBeTruthy();
  });
});
