import { randomUUID } from "node:crypto";
import { Service } from "@deepseek-ai/cordis";
import type { Context } from "@deepseek-ai/cordis";
import {
  assertReferenceTarget, finalizeExplain, listActiveJobs, listReferenceEntries, loadPrepare, markRunningJobsInterrupted,
  readExplainPublicationState, readReferenceText, readJobRecord, readPreparedSources, referenceTargetOf, restoreExplainPublicationState, updateJobRecord, jobRecordRelativePath, type ExplainJobRecord, type ExplainReferenceTarget,
} from "./explain-artifacts.ts";
import { withExplainFileLock, writeExplainFile } from "@icomposer/workbench-contracts/ici-explain";
import { graphBaseDir, legacyGraphBaseDir, readManifest } from "./storage.ts";
import { ICI_ENGINE_VERSION } from "./engine-version.ts";

interface AgentLike { readonly id?: string; readonly ctx?: unknown; readonly options?: { provider?: string; model?: string }; whenIdle(): Promise<void>; runMaintenance<T>(task: (signal: AbortSignal) => Promise<T>): Promise<T>; }
interface ChildAgent { readonly id: string; readonly options?: { provider?: string; model?: string }; followup(message: unknown): void; whenIdle(): Promise<void>; cancel(cause: unknown): void; }
interface AgentHandle { readonly agent: ChildAgent; dispose(): Promise<void>; }
interface AgentsFace { roots?(): readonly AgentLike[]; create?(options: Record<string, unknown>): Promise<AgentHandle>; withInitiator?<T>(agent: AgentLike, operation: () => T): T; }
interface LlmExplainFace { listProviders(): readonly { id: string }[]; resolveModelInfo?(provider: string, model: string, signal?: AbortSignal): Promise<unknown>; }
interface BindingFace { list(): Promise<{ ok: boolean; value?: readonly { workspaceId: string; canonicalPath: string }[] }>; get(id: string): Promise<{ ok: boolean; value?: { canonicalPath: string } }>; }

export const MAX_EXPLAIN_PROMPT_BYTES = 256 * 1024;
const MAX_FLOW_ITEMS = 64;
const MAX_TIMER_MS = 2_147_000_000;
const MAX_READ_FILES = 20;
const MAX_REFERENCE_BYTES = 256 * 1024;
const MAX_LIST_ENTRIES = 200;
const MAX_SUBMIT_ATTEMPTS = 3;
const EVIDENCE_PATTERN = "^(?:[A-Za-z0-9._-]+\\/)*[A-Za-z0-9._-]+#\\d+(?:-\\d+)?$";
const SUBMIT_REPAIR = "schema-invalid: submit exactly technical/business strings, flow string[], and evidence string[]; evidence must use only relative prepared/read paths as path#N or path#N-M (#, never : or objects).";
const SECRET_PATTERN = /(authorization\s*:|bearer\s+|access[_-]?token|refresh[_-]?token|client[_-]?secret|api[_-]?key)/i;
const ABSOLUTE_PATH_PATTERN = /(?:^|[\s"'`])\/(?:Users|home|private|tmp|var|opt|etc)\/|[A-Za-z]:[\\/]/i;
const explainJobTails = new Map<string, Promise<void>>();
async function withExplainJobTransaction<T>(root: string, jobId: string, task: () => Promise<T>): Promise<T> { const key = `${root}\0${jobId}`; const previous = explainJobTails.get(key) ?? Promise.resolve(); let release!: () => void; const current = new Promise<void>(resolve => { release = resolve; }); explainJobTails.set(key, current); await previous; try { return await task(); } finally { release(); if (explainJobTails.get(key) === current) explainJobTails.delete(key); } }
async function currentGraphManifest(root: string, workspaceId: string): Promise<{ engineVersion?: string; sourceFingerprint?: string; graphDigest?: string } | null> { return readManifest(graphBaseDir(root, workspaceId), legacyGraphBaseDir(root, workspaceId)); }
async function assertFreshJob(root: string, job: ExplainJobRecord): Promise<Awaited<ReturnType<typeof loadPrepare>>> { const prepare = await loadPrepare(root, job.prepareArtifactPath); const graph = await currentGraphManifest(root, job.workspaceId); if (!graph || job.engineVersion !== ICI_ENGINE_VERSION || prepare.manifest.engineVersion !== ICI_ENGINE_VERSION || graph.engineVersion !== ICI_ENGINE_VERSION || graph.sourceFingerprint !== job.sourceFingerprint || graph.graphDigest !== job.graphDigest || prepare.manifest.sourceFingerprint !== job.sourceFingerprint || prepare.manifest.graphDigest !== job.graphDigest) throw new Error("stale-snapshot"); return prepare; }
async function publishFinal(root: string, running: ExplainJobRecord, analysis: { technical: string; business: string; flow: string[]; evidence: string[] }, signal: AbortSignal, folderReads: readonly { path: string; sha256: string }[], target: ExplainReferenceTarget, childSessionId?: string): Promise<boolean> { if (signal.aborted) return false; return withExplainJobTransaction(root, running.jobId, async () => withExplainFileLock(root, jobRecordRelativePath(running.jobId), async () => { const current = await readJobRecord(root, running.jobId); if (!current || current.status !== "running" || signal.aborted) return false; await assertFreshJob(root, current); const previousState = await readExplainPublicationState(root); try { await finalizeExplain(root, current.workspaceId, current.prepareArtifactPath, { api: analysis }, { sourceFingerprint: current.sourceFingerprint, graphDigest: current.graphDigest, engineVersion: current.engineVersion! }, undefined, current.jobId, folderReads, target.path, target); const committed = { ...current, ...(childSessionId === undefined ? {} : { childSessionId }), status: "final" as const, finishedAt: new Date().toISOString(), revision: current.revision + 1, updatedAt: new Date().toISOString() }; await writeExplainFile(root, jobRecordRelativePath(current.jobId), `${JSON.stringify(committed, null, 2)}\n`, { skipLock: true }); return true; } catch (cause) { await restoreExplainPublicationState(root, previousState).catch(() => undefined); throw cause; } })); }
function fixedText(value: unknown, max: number): value is string { return typeof value === "string" && value.trim().length > 0 && value.length <= max && !SECRET_PATTERN.test(value) && !value.startsWith("/") && !ABSOLUTE_PATH_PATTERN.test(value); }
function evidence(value: unknown): value is readonly string[] { return Array.isArray(value) && value.length > 0 && value.length <= 64 && value.every(item => typeof item === "string" && item.length <= 400 && !SECRET_PATTERN.test(item) && /^(?:[A-Za-z0-9._-]+\/)*[A-Za-z0-9._-]+#\d+(?:-\d+)?$/.test(item) && !item.split("#", 1)[0].split("/").some(part => part === "." || part === ".." || part === ".metadata")); }
/** Legacy helper retained for old callers; aggregate synthesis does not use per-node output. */
export function validNodeAnalysis(value: unknown): boolean { if (typeof value !== "object" || value === null) return false; const row = value as Record<string, unknown>; if (Object.keys(row).length === 2 && fixedText(row.node_id, 512) && fixedText(row.unavailable_reason, 1000)) return true; return Object.keys(row).length === 4 && fixedText(row.node_id, 512) && fixedText(row.technical, 12_000) && fixedText(row.business, 12_000) && evidence(row.evidence); }
function containsUnsafeText(value: unknown): boolean { if (typeof value === "string") return value.startsWith("/") || SECRET_PATTERN.test(value) || ABSOLUTE_PATH_PATTERN.test(value); if (Array.isArray(value)) return value.some(containsUnsafeText); if (typeof value === "object" && value !== null) return Object.values(value).some(containsUnsafeText); return false; }
function unsafeAnalysis(value: unknown): boolean { return containsUnsafeText(value); }
function strictAnalysis(value: unknown, target: ExplainReferenceTarget, verifiedPaths: ReadonlySet<string>): value is { technical: string; business: string; flow: string[]; evidence: string[] } { if (typeof value !== "object" || value === null) return false; const row = value as Record<string, unknown>; return Object.keys(row).length === 4 && ["technical", "business", "flow", "evidence"].every(key => Object.prototype.hasOwnProperty.call(row, key)) && fixedText(row.technical, 12_000) && fixedText(row.business, 12_000) && Array.isArray(row.flow) && row.flow.length <= MAX_FLOW_ITEMS && row.flow.every(item => fixedText(item, 500)) && evidence(row.evidence) && row.evidence.every(item => { const path = String(item).split("#", 1)[0]; const targetPath = target.kind === "file" ? path === target.path : target.kind === "directory" && (target.path === "" || path.startsWith(`${target.path}/`)); return verifiedPaths.has(path) && (targetPath || path.startsWith("src/") || path.startsWith("docs/")); }); }
function sourcePrompt(prepare: Awaited<ReturnType<typeof loadPrepare>>, sources: readonly { nodeId?: string; path: string; startLine?: number; endLine?: number; content: string }[], target: ExplainReferenceTarget): string { const targetText = JSON.stringify(target); const targetInstruction = target.kind === "none" ? "No optional reference selected; use only the prepared source ranges; do not call ici_explain_list or ici_explain_read." : target.kind === "file" ? `Selected file ${target.path}; use ici_explain_read only if needed, then submit (listing is optional).` : `Selected directory ${target.path || "."}; use ici_explain_list/read only if needed, then submit.`; return [`You are a dedicated read-only explanation agent for API ${prepare.api.name}. Workspace-relative reference target: ${targetText}. ${targetInstruction} Use only the three tools ici_explain_list, ici_explain_read, ici_explain_submit. Never use absolute paths, shell/network/write tools, or any other tool. Read only useful text files (at most 20 files and 256 KiB total), then call ici_explain_submit with a valid object; schema-invalid may be corrected and retried up to three attempts. Submit exactly technical/business strings, flow string[], and evidence string[]. Evidence must use only prepared/read relative paths as path#N or path#N-M; # is mandatory, never use : or objects. Never emit a final answer instead of submit.`, `Prepare metadata: ${JSON.stringify({ api: prepare.api, manifest: prepare.manifest, prepareId: prepare.prepareId, contextHash: prepare.contextHash })}`, `Prepare call chain: ${JSON.stringify(prepare.callChain)}`, ...sources.map(source => `--- prepared source ${source.nodeId ?? "api"} ${source.path}#${source.startLine ?? 1}-${source.endLine ?? 1}\n${source.content}`)].join("\n"); }
function correctiveFollowup(target: ExplainReferenceTarget, aborted = false): string { const prefix = aborted ? "Your previous turn was aborted. " : ""; const submit = "Call ici_explain_submit now with exactly technical/business strings, flow string[], and evidence string[] using relative path#N or path#N-M (#, never :)."; return target.kind === "none" ? `${prefix}No optional reference selected; do not call ici_explain_list or ici_explain_read. ${submit}` : `${prefix}Use ici_explain_list/read only if needed for the selected reference; do not require both. ${submit}`; };
function toolOutput(value: unknown): Array<{ type: "text"; text: string }> { return [{ type: "text", text: JSON.stringify(value) }]; }
function utf8Bytes(value: unknown): number { try { return Buffer.byteLength(JSON.stringify(value), "utf8"); } catch { return Number.MAX_SAFE_INTEGER; } }
function explainRequestBytes(value: unknown): number { const row = value as Record<string, unknown> | null; return utf8Bytes({ provider: row?.provider, model: row?.model, system: row?.system, messages: row?.messages, tools: row?.tools }); }
function childMessage(text: string): unknown { return { id: `ici-explain-${randomUUID()}`, role: "user", content: [{ type: "text", text }], source: { kind: "plugin", plugin: "icomposer-code-intelligence", form: "explain" } }; }
function toolSchema(properties: Record<string, unknown>, required: readonly string[] = []): Record<string, unknown> { return { type: "object", additionalProperties: false, properties, required: [...required] }; }
async function* strictChildStream(source: AsyncIterable<any>): AsyncGenerator<any> { let finished = false; for await (const chunk of source) { if (finished) throw new Error("stream-after-finish"); if (chunk?.type === "finish") { if (chunk.reason?.kind === "aborted") throw new Error("stream-aborted"); if (typeof chunk.reason?.kind !== "string" || !["stop", "tool-calls"].includes(chunk.reason.kind)) throw new Error("stream-invalid"); finished = true; } yield chunk; } if (!finished) throw new Error("stream-no-finish"); }
async function* monitoredChildStream(source: AsyncIterable<any>, fail: (error: unknown) => void): AsyncGenerator<any> { try { yield* strictChildStream(source); } catch (error) { fail(error); throw error; } }

/** Create one fresh restricted background Agent and await its controlled submit boundary. */
async function runDedicatedAgent(ctx: Context, root: string, job: Awaited<ReturnType<typeof readJobRecord>> & {}, prepare: Awaited<ReturnType<typeof loadPrepare>>, sources: readonly { nodeId?: string; path: string; startLine?: number; endLine?: number; content: string }[], signal: AbortSignal, parent?: AgentLike): Promise<{ analysis: { technical: string; business: string; flow: string[]; evidence: string[] }; folderReads: readonly { path: string; sha256: string }[]; childSessionId: string }> {
  const agents = ctx.get("agents") as AgentsFace | undefined; if (!agents?.create) throw new Error("model-failed");
  const target = referenceTargetOf(job); await assertReferenceTarget(root, target); const initialPrompt = sourcePrompt(prepare, sources, target); const basePromptBytes = Buffer.byteLength(initialPrompt, "utf8"); if (basePromptBytes > MAX_EXPLAIN_PROMPT_BYTES) throw new Error("input-too-large");
  let childRef: ChildAgent | undefined; let toolFailureReason: string | undefined; let streamAborted = false; let resolveSubmitted: (value: { technical: string; business: string; flow: string[]; evidence: string[] }) => void = () => undefined; const submitted = new Promise<{ technical: string; business: string; flow: string[]; evidence: string[] }>(resolve => { resolveSubmitted = resolve; }); let submittedOnce = false; let submitAttempts = 0; let toolFailure = false; let listCalls = 0; let readCalls = 0; let readBytes = 0; let toolOutputBytes = 0; const verifiedPaths = new Set<string>(sources.map(source => source.path)); const folderReads: Array<{ path: string; sha256: string }> = []; const reserveToolOutput = (value: unknown): void => { toolOutputBytes += utf8Bytes(value); if (basePromptBytes + toolOutputBytes > MAX_EXPLAIN_PROMPT_BYTES) { toolFailure = true; toolFailureReason = "input-too-large"; childRef?.cancel("tool-failed"); throw new Error("input-too-large"); } };
  const setup = (childCtx: any): void => {
    const tools = childCtx.tools as { restrict(filter: { allow: readonly string[] }): unknown; register(definition: Record<string, unknown>): unknown };
    tools.restrict({ allow: [] });
    tools.register({ name: "ici_explain_list", description: target.kind === "none" ? "No optional reference selected; do not call this tool. It returns an empty list without filesystem access." : "List text files and child directories under the selected workspace-relative reference target. Use only when needed; a selected file cannot be expanded.", parameters: toolSchema({ path: { type: "string", description: "Workspace-relative subpath; omitted for the target root." } }), output: { schema: toolSchema({ result: { type: "array" } }, ["result"]), render: (_a: unknown, value: unknown) => toolOutput(value) }, execute: async (raw: Record<string, unknown>) => { if (++listCalls > 20) { toolFailure = true; toolFailureReason = "tool-limit"; childRef?.cancel("tool-failed"); throw new Error("tool-limit"); } try { const subpath = typeof raw.path === "string" ? raw.path : ""; const output = { entries: (await listReferenceEntries(root, target, subpath)).filter(entry => entry.kind === "directory" || entry.supported === true).slice(0, MAX_LIST_ENTRIES) }; reserveToolOutput(output); return output; } catch (error) { toolFailure = true; const message = error instanceof Error && ["tool-limit", "input-too-large", "folder-forbidden", "folder-oversize"].includes(error.message) ? error.message : "folder-forbidden"; toolFailureReason = message; childRef?.cancel("tool-failed"); throw new Error(message); } } });
    tools.register({ name: "ici_explain_read", description: target.kind === "none" ? "No optional reference selected; do not call this tool. It returns folder-forbidden without filesystem access." : "Read one file under the selected workspace-relative reference target, subject to strict byte and call limits; use only when needed.", parameters: toolSchema({ path: { type: "string", description: "Workspace-relative file path." } }, ["path"]), output: { schema: toolSchema({ path: { type: "string" }, content: { type: "string" }, bytes: { type: "integer" }, sha256: { type: "string" } }, ["path", "content", "bytes", "sha256"]), render: (_a: unknown, value: unknown) => toolOutput(value) }, execute: async (raw: Record<string, unknown>) => { if (++readCalls > MAX_READ_FILES) { toolFailure = true; toolFailureReason = "tool-limit"; childRef?.cancel("tool-failed"); throw new Error("tool-limit"); } try { if (typeof raw.path !== "string") throw new Error("folder-forbidden"); const file = await readReferenceText(root, target, raw.path); readBytes += file.bytes; if (readBytes > Math.min(MAX_REFERENCE_BYTES, Math.max(0, MAX_EXPLAIN_PROMPT_BYTES - basePromptBytes))) { toolFailureReason = "input-too-large"; throw new Error("input-too-large"); } verifiedPaths.add(file.path); folderReads.push({ path: file.path, sha256: file.sha256 }); reserveToolOutput(file); return file; } catch (error) { const message = error instanceof Error && ["tool-limit", "folder-oversize", "input-too-large", "folder-forbidden"].includes(error.message) ? error.message : "folder-forbidden"; if (!(target.kind === "none" && message === "folder-forbidden")) { toolFailure = true; toolFailureReason = message; childRef?.cancel("tool-failed"); } throw new Error(message); } } });
    tools.register({ name: "ici_explain_submit", description: "Submit exactly one strict aggregate API explanation; this is the only completion boundary. technical/business are strings, flow is string[], and evidence is string[] using relative path#N or path#N-M (use #, never : or objects).", parameters: toolSchema({ technical: { type: "string", minLength: 1, maxLength: 12000, description: "Factual technical explanation." }, business: { type: "string", minLength: 1, maxLength: 12000, description: "Factual business explanation." }, flow: { type: "array", minItems: 0, maxItems: MAX_FLOW_ITEMS, items: { type: "string", minLength: 1, maxLength: 500 }, description: "Ordered factual flow steps as strings." }, evidence: { type: "array", minItems: 1, maxItems: 64, items: { type: "string", minLength: 1, maxLength: 400, pattern: EVIDENCE_PATTERN }, description: "Relative prepared/read source references; each must be path#N or path#N-M, never path:N or an object." } }, ["technical", "business", "flow", "evidence"]), output: { schema: toolSchema({ accepted: { type: "boolean" } }, ["accepted"]), render: (_a: unknown, value: unknown) => toolOutput(value) }, execute: async (raw: Record<string, unknown>) => { if (toolFailure) throw new Error(toolFailureReason ?? "model-failed"); if (submittedOnce) { toolFailure = true; toolFailureReason = "schema-invalid"; childRef?.cancel("tool-failed"); throw new Error("schema-invalid"); } if (!strictAnalysis(raw, target, verifiedPaths)) { toolFailureReason = "schema-invalid"; if (unsafeAnalysis(raw) || ++submitAttempts >= MAX_SUBMIT_ATTEMPTS) { toolFailure = true; childRef?.cancel("tool-failed"); throw new Error("schema-invalid"); } throw new Error(SUBMIT_REPAIR); } submittedOnce = true; resolveSubmitted(raw as { technical: string; business: string; flow: string[]; evidence: string[] }); return { accepted: true }; } });
    if (typeof childCtx.on === "function") childCtx.on("llm/stream", (options: unknown, next: () => AsyncIterable<any>) => { if (explainRequestBytes(options) > MAX_EXPLAIN_PROMPT_BYTES) { toolFailure = true; toolFailureReason = "input-too-large"; childRef?.cancel("tool-failed"); throw new Error("input-too-large"); } return monitoredChildStream(next(), error => { const message = error instanceof Error ? error.message : "stream-error"; if (message === "stream-aborted") { streamAborted = true; return; } toolFailure = true; toolFailureReason = message; childRef?.cancel("tool-failed"); }); }, { prepend: true });
    childCtx.systemPrompt.section({ name: `ici-explain-child:${job.jobId}`, order: 120, text: `This is a dedicated read-only ICI explanation child. Only ici_explain_list, ici_explain_read, ici_explain_submit are available. Workspace-relative reference target is ${JSON.stringify(target)}${target.kind === "none" ? "; no optional reference selected; use prepared source ranges; do not call ici_explain_list or ici_explain_read; submit only" : "; use ici_explain_list/read only if needed; do not require both; then submit"}. Evidence must be string[] with relative path#N or path#N-M (#, never :). Never use absolute paths or shell/network/write tools.` });
  };
  const childSessionId = randomUUID(); const create = (): Promise<AgentHandle> => agents.create!({ sessionId: childSessionId, meta: { cwd: root, ...(parent?.id ? { parentSession: parent.id } : {}), origin: "subagent", delegationDepth: 1 }, agentOptions: { provider: job.provider!, model: job.model!, maxTokens: 4096 }, setup, signal }); const handle = parent && agents.withInitiator ? await agents.withInitiator(parent, create) : await create();
  const child = handle.agent; childRef = child; const abortChild = (): void => { try { child.cancel("cancelled"); } catch { /* disposal below */ } }; signal.addEventListener("abort", abortChild, { once: true });
  try {
    const waitForTurn = async (): Promise<{ kind: "submitted"; value: { technical: string; business: string; flow: string[]; evidence: string[] } } | { kind: "idle" } | { kind: "aborted" }> => {
      const idle = child.whenIdle().then(() => ({ kind: "idle" as const }));
      let onAbort: (() => void) | undefined;
      const aborted = new Promise<{ kind: "aborted" }>(resolve => { onAbort = () => resolve({ kind: "aborted" }); if (signal.aborted) onAbort(); else signal.addEventListener("abort", onAbort, { once: true }); });
      try { return await Promise.race([submitted.then((value: { technical: string; business: string; flow: string[]; evidence: string[] }) => ({ kind: "submitted" as const, value })), idle, aborted]); }
      finally { if (onAbort) signal.removeEventListener("abort", onAbort); }
    };
    try {
      const current = await readJobRecord(root, job.jobId); if (current && current.status === "running" && current.revision === job.revision) await updateJobRecord(root, job.jobId, job.revision, { childSessionId }).catch(() => undefined);
    } catch { /* best-effort attribution */ }
    child.followup(childMessage(initialPrompt));
    let outcome = await waitForTurn();
    if (outcome.kind === "idle") {
      if (toolFailure && toolFailureReason !== "stream-aborted") throw new Error(toolFailureReason ?? "model-failed");
      if (streamAborted) {
        streamAborted = false;
        child.followup(childMessage(correctiveFollowup(target, true)));
        outcome = await waitForTurn();
      } else {
        child.followup(childMessage(correctiveFollowup(target)));
        outcome = await waitForTurn();
      }
    }
    if (outcome.kind !== "submitted") throw new Error(outcome.kind === "aborted" ? "stream-aborted" : streamAborted ? "stream-aborted" : toolFailureReason ?? "model-failed");
    try { child.cancel("cancelled"); } catch { /* stop after submit */ }
    return { analysis: outcome.value, folderReads, childSessionId };
  } finally { signal.removeEventListener("abort", abortChild); try { child.cancel("cancelled"); } catch { /* already idle */ } await handle.dispose(); }
}

export async function processConfirmedJob(llm: LlmExplainFace, root: string, jobId: string, signal: AbortSignal, ctx?: Context, parent?: AgentLike): Promise<void> {
  const started = await readJobRecord(root, jobId); if (!started || !["scheduled", "confirmed"].includes(started.status)) return;
  if (!started.provider || !started.model) { await updateJobRecord(root, jobId, started.revision, { status: "failed", error: "confirmation-invalid" }).catch(() => undefined); return; }
  let registered = false; try { registered = llm.listProviders().some(provider => provider.id === started.provider); if (registered && llm.resolveModelInfo) await llm.resolveModelInfo(started.provider, started.model, signal); } catch { registered = false; }
  if (!registered || !ctx) { await updateJobRecord(root, jobId, started.revision, { status: "failed", error: "confirmation-invalid" }).catch(() => undefined); return; }
  if (started.notBefore && Date.parse(started.notBefore) > Date.now()) return;
  let preflightPrepare: Awaited<ReturnType<typeof loadPrepare>>;
  try { preflightPrepare = await assertFreshJob(root, started); } catch { await updateJobRecord(root, jobId, started.revision, { status: "failed", error: "stale-snapshot" }).catch(() => undefined); return; }
  const running = await updateJobRecord(root, jobId, started.revision, { status: "running", startedAt: new Date().toISOString() }).catch(() => null); if (!running) return;
  try {
    const target = referenceTargetOf(running); await assertReferenceTarget(root, target);
    const prepare = preflightPrepare; if (prepare.workspaceId !== running.workspaceId || prepare.api.id !== running.apiId || prepare.api.name !== running.apiName || prepare.prepareId !== running.prepareId || prepare.contextHash !== running.contextHash || prepare.manifest.sourceFingerprint !== running.sourceFingerprint || prepare.manifest.graphDigest !== running.graphDigest) throw new Error("confirmation-invalid");
    if (running.docs.some(doc => !prepare.references.some(ref => ref.readable && ref.path === doc.path && ref.sha256 === doc.sha256))) throw new Error("confirmation-invalid");
    const sources: Array<{ nodeId?: string; path: string; startLine?: number; endLine?: number; content: string }> = []; for (const ref of prepare.sources) if (ref.readable) sources.push(...await readPreparedSources(root, running.workspaceId, running.prepareArtifactPath, [ref.nodeId!], [], signal)); if (sources.some(source => SECRET_PATTERN.test(source.content) || ABSOLUTE_PATH_PATTERN.test(source.content))) throw new Error("source-forbidden");
    const prompt = sourcePrompt(prepare, sources, target); if (Buffer.byteLength(prompt, "utf8") > MAX_EXPLAIN_PROMPT_BYTES) throw new Error("input-too-large"); signal.throwIfAborted(); const latestBeforeChild = await readJobRecord(root, jobId); if (!latestBeforeChild || latestBeforeChild.status !== "running") return;
    const completed = await runDedicatedAgent(ctx, root, running, prepare, sources, signal, parent); const published = await publishFinal(root, running, completed.analysis, signal, completed.folderReads, target, completed.childSessionId); if (!published) return;
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : "model-failed"; const externalAbort = signal.aborted || cause instanceof DOMException; const aborted = externalAbort || message === "aborted"; const known = new Set(["confirmation-invalid", "source-changed", "folder-changed", "stale-snapshot", "prepare-invalidated", "input-too-large", "output-oversize", "stream-error", "stream-incomplete", "stream-tool-call", "stream-invalid", "stream-aborted", "stream-no-finish", "stream-after-finish", "schema-invalid", "tool-limit", "source-forbidden", "folder-forbidden", "folder-oversize"]); const error = aborted ? "cancelled" : known.has(message) ? message : "model-failed";
    await withExplainJobTransaction(root, jobId, async () => { const latest = await readJobRecord(root, jobId); if (latest && !["final", "cancelled"].includes(latest.status)) await updateJobRecord(root, jobId, latest.revision, { status: aborted ? "cancelled" : "failed", finishedAt: new Date().toISOString(), error }).catch(() => undefined); });
  }
}

export class ExplainScheduler extends Service {
  static inject = ["agents", "llm", "workspaceBinding"] as const;
  #attached = new WeakSet<object>(); #requested = new WeakSet<object>(); #runs = new WeakMap<object, Promise<void>>(); #waiting = new WeakSet<object>(); #controllers = new Map<string, AbortController>(); #inflight = new Set<Promise<void>>(); #disposePromise?: Promise<void>; #timers = new Map<string, ReturnType<typeof setTimeout>>(); #timerTargets = new Map<string, number>(); #recovered = new Set<string>(); #disposed = false;
  constructor(ctx: Context) { super(ctx, "iciExplainScheduler" as never); this.cancelJob = this.cancelJob.bind(this); this.poke = this.poke.bind(this); }
  protected [Service.init](): void { this.ctx.effect(() => () => this.dispose(), "iciExplainScheduler.dispose"); void this.attachRoots(); const on = (this.ctx as unknown as { on(event: string, listener: () => void): () => boolean }).on.bind(this.ctx); for (const event of ["agent/idle", "agent/status", "agent/created"]) try { on(event, () => void this.attachRoots()); } catch { /* optional */ } }
  private async attachRoots(): Promise<void> { if (this.#disposed) return; const roots = (this.ctx.get("agents") as AgentsFace | undefined)?.roots?.() ?? []; const binding = this.ctx.get("workspaceBinding") as BindingFace | undefined; if (binding) { const listed = await binding.list().catch(() => ({ ok: false, value: undefined } as Awaited<ReturnType<BindingFace["list"]>>)); if (listed.ok) for (const row of listed.value ?? []) { if (!this.#recovered.has(row.canonicalPath)) { this.#recovered.add(row.canonicalPath); await markRunningJobsInterrupted(row.canonicalPath); } await this.armScheduled(row.canonicalPath); } } for (const agent of roots) { if (this.#attached.has(agent)) continue; this.#attached.add(agent); this.requestDrive(agent); } }
  private async armScheduled(root: string): Promise<void> { for (const job of await listActiveJobs(root)) if (job.status === "scheduled" && job.notBefore) this.armTimer(job); }
  private armTimer(job: ExplainJobRecord): void { const target = Date.parse(job.notBefore ?? ""); if (!Number.isFinite(target)) return; const delay = Math.min(MAX_TIMER_MS, Math.max(0, target - Date.now())); const existing = this.#timers.get(job.jobId); if (existing && this.#timerTargets.get(job.jobId) === target) return; if (existing) clearTimeout(existing); const timer = setTimeout(() => { this.#timers.delete(job.jobId); this.#timerTargets.delete(job.jobId); this.poke(); }, delay); this.#timers.set(job.jobId, timer); this.#timerTargets.set(job.jobId, target); }
  requestDrive(agent: AgentLike): void { if (this.#disposed) return; this.#requested.add(agent); if (this.#runs.has(agent)) return; const run = this.drain(agent).finally(() => { this.#runs.delete(agent); if (this.#requested.has(agent)) this.requestDrive(agent); }); this.#runs.set(agent, run); }
  private async drain(agent: AgentLike): Promise<void> { while (this.#requested.has(agent) && !this.#disposed) { this.#requested.delete(agent); await this.driveOnce(agent); } }
  private async driveOnce(agent: AgentLike): Promise<void> { const binding = this.ctx.get("workspaceBinding") as BindingFace | undefined; const llm = this.ctx.get("llm") as LlmExplainFace | undefined; if (!binding || !llm) return; const listed = await binding.list().catch(() => ({ ok: false, value: undefined } as Awaited<ReturnType<BindingFace["list"]>>)); if (!listed.ok) return; let job: ExplainJobRecord | undefined; for (const row of listed.value ?? []) { const candidate = (await listActiveJobs(row.canonicalPath)).find(item => ["scheduled", "confirmed"].includes(item.status)); if (candidate?.notBefore && Date.parse(candidate.notBefore) > Date.now()) { this.armTimer(candidate); continue; } if (candidate && !this.#controllers.has(candidate.jobId)) { job = candidate; break; } } if (!job) return; const resolved = await binding.get(job.workspaceId); if (!resolved.ok || !resolved.value) return; try { await agent.whenIdle(); } catch { return; } if (this.#disposed) return; try { await agent.runMaintenance(async signal => { const controller = new AbortController(); this.#controllers.set(job!.jobId, controller); const relay = (): void => controller.abort(); signal.addEventListener("abort", relay, { once: true }); const run = processConfirmedJob(llm, resolved.value!.canonicalPath, job!.jobId, controller.signal, this.ctx, agent).catch(() => undefined).finally(() => { signal.removeEventListener("abort", relay); this.#controllers.delete(job!.jobId); this.#inflight.delete(run); }); this.#inflight.add(run); if (this.#disposed) controller.abort(); }); } catch { /* busy; next idle */ } finally { this.rearmAtNextIdle(agent); } }
  private rearmAtNextIdle(agent: AgentLike): void { if (this.#disposed || this.#waiting.has(agent)) return; this.#waiting.add(agent); void agent.whenIdle().then(() => { this.#waiting.delete(agent); this.requestDrive(agent); }, () => { this.#waiting.delete(agent); }); }
  async cancelJob(jobId: string): Promise<boolean> { this.#controllers.get(jobId)?.abort(); const binding = this.ctx.get("workspaceBinding") as BindingFace | undefined; if (!binding) return false; const listed = await binding.list().catch(() => ({ ok: false, value: undefined } as Awaited<ReturnType<BindingFace["list"]>>)); for (const row of listed.value ?? []) { const cancelled = await withExplainJobTransaction(row.canonicalPath, jobId, async () => { for (let attempt = 0; attempt < 20; attempt++) { const record = await readJobRecord(row.canonicalPath, jobId); if (!record) return false; if (record.status === "cancelled") return true; if (!["awaiting-input", "scheduled", "confirmed", "running"].includes(record.status)) return false; const updated = await updateJobRecord(row.canonicalPath, jobId, record.revision, { status: "cancelled", error: "cancelled" }).then(() => true).catch(() => false); if (updated) return true; await new Promise(resolve => setTimeout(resolve, 5)); } return (await readJobRecord(row.canonicalPath, jobId))?.status === "cancelled"; }); if (cancelled) { const timer = this.#timers.get(jobId); if (timer) clearTimeout(timer); this.#timers.delete(jobId); this.#timerTargets.delete(jobId); } if (cancelled || (await readJobRecord(row.canonicalPath, jobId))?.status === "final") return cancelled; } return false; }
  poke(): void { if (this.#disposed) return; const roots = (this.ctx.get("agents") as AgentsFace | undefined)?.roots?.() ?? []; for (const agent of roots) this.requestDrive(agent); }
  dispose(): Promise<void> { if (this.#disposePromise) return this.#disposePromise; this.#disposed = true; for (const controller of this.#controllers.values()) controller.abort(); for (const timer of this.#timers.values()) clearTimeout(timer); this.#timers.clear(); this.#timerTargets.clear(); this.#disposePromise = (async () => { while (this.#inflight.size > 0) await Promise.all([...this.#inflight]); this.#controllers.clear(); })(); return this.#disposePromise; }
}
