import { lstat, readdir, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import type { DiagnosticsResult } from "./types.ts";

/** Directory names generated by the atomic promote that are safe to delete. */
export const RESIDUE_PREFIXES = ["staging-", "stale-"] as const;

export function isResidueName(name: string): boolean {
  return RESIDUE_PREFIXES.some(prefix => name.startsWith(prefix));
}

export interface MaintenancePaths {
  /** Absolute workspace-owned or legacy directory for one workspace. */
  readonly workspaceDir: string;
  readonly fallbackWorkspaceDir?: string;
  readonly searchWorkspaceDirs?: readonly string[];
}

export interface MaintenanceFileFacts {
  readonly manifest: string | null;
  readonly nodesExists: boolean;
  readonly edgesExists: boolean;
  readonly searchVectors: number;
}

async function readJson(path: string): Promise<Record<string, unknown> | null> {
  try {
    return JSON.parse(await readFile(path, "utf8")) as Record<string, unknown>;
  } catch {
    return null;
  }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await lstat(path);
    return true;
  } catch {
    return false;
  }
}

/** Rust doctor semantics: required-file existence + counts + vector count. */
export async function collectFileFacts(paths: MaintenancePaths): Promise<MaintenanceFileFacts> {
  const current = join(paths.workspaceDir, "graph", "current");
  const manifest = await readJson(join(current, "manifest.json"));
  const nodesExists = await fileExists(join(current, "nodes.json"));
  const edgesExists = await fileExists(join(current, "edges.json"));
  let searchVectors = 0;
  const searchDirs = paths.searchWorkspaceDirs ?? [paths.workspaceDir, ...(paths.fallbackWorkspaceDir === undefined ? [] : [paths.fallbackWorkspaceDir])];
  for (const directory of searchDirs) {
    if (searchVectors > 0) break;
    try {
      const text = await readFile(join(directory, "graph", "search", "api_embeddings.jsonl"), "utf8");
      for (const line of text.split("\n")) if (line.trim()) searchVectors += 1;
    } catch { /* try fallback */ }
  }
  return {
    manifest: manifest !== null ? JSON.stringify(manifest) : null,
    nodesExists,
    edgesExists,
    searchVectors,
  };
}

/**
 * Residue cleanup plan: every `staging-*` / `stale-*` entry under the
 * workspace ICI tree (graph and search levels). Only generated residue
 * naming patterns are ever listed.
 */
export async function planCleanup(workspaceDir: string): Promise<string[]> {
  const out: string[] = [];
  const scanLevels = [join(workspaceDir, "graph"), join(workspaceDir, "graph", "search")];
  for (const level of scanLevels) {
    let names: string[] = [];
    try { names = await readdir(level); } catch { continue; }
    for (const name of names) {
      if (isResidueName(name)) out.push(join(level, name));
    }
  }
  return out.sort();
}

/**
 * Delete exactly the planned paths. Every path is re-verified with lstat:
 * it must still exist, sit under the workspace ICI tree, and carry a
 * generated-residue name — anything else is skipped (TOCTOU guard).
 */
export async function applyCleanup(
  workspaceDir: string,
  expectedPaths: readonly string[],
): Promise<{ removed: string[]; skipped: string[] }> {
  const removed: string[] = [];
  const skipped: string[] = [];
  const planned = new Set(expectedPaths);
  for (const path of planned) {
    const normalized = join(path);
    if (!normalized.startsWith(workspaceDir + "/")) {
      skipped.push(normalized);
      continue;
    }
    const name = normalized.split("/").pop() ?? "";
    if (!isResidueName(name)) {
      skipped.push(normalized);
      continue;
    }
    try {
      await lstat(normalized);
    } catch {
      skipped.push(normalized);
      continue;
    }
    try {
      await rm(normalized, { recursive: true, force: true });
      removed.push(normalized);
    } catch {
      skipped.push(normalized);
    }
  }
  // Paths planned but not present anymore are silently dropped (idempotent).
  return { removed, skipped };
}

export interface DiagnosticsView {
  readonly workspaceId: string;
  readonly indexPaths: { readonly graphCurrent: string; readonly searchJsonl: string };
  readonly schemaVersion: number;
  readonly engineVersion: string;
  readonly builtAt: string | null;
  readonly nodeCount: number;
  readonly edgeCount: number;
  readonly searchVectors: number;
  readonly stale: boolean;
  readonly requiredFiles: { readonly nodes: boolean; readonly edges: boolean; readonly manifest: boolean };
}

/** Build the diagnostics projection for one workspace ICI tree. */
export function buildDiagnosticsView(
  workspaceDir: string,
  workspaceId: string,
  engineVersion: string,
  manifestText: string | null,
  stale: boolean,
  fileFacts?: { nodesExists: boolean; edgesExists: boolean },
): DiagnosticsView {
  interface ParsedManifest { builtAt?: string; nodeCount?: number; edgeCount?: number }
  let parsed: ParsedManifest | null = null;
  try { parsed = JSON.parse(manifestText ?? "null") as ParsedManifest; } catch { parsed = null; }
  const manifest = parsed;
  return {
    workspaceId,
    indexPaths: {
      graphCurrent: join(workspaceDir, "graph", "current"),
      searchJsonl: join(workspaceDir, "graph", "search", "api_embeddings.jsonl"),
    },
    schemaVersion: 1,
    engineVersion,
    builtAt: manifest?.builtAt ?? null,
    nodeCount: manifest?.nodeCount ?? 0,
    edgeCount: manifest?.edgeCount ?? 0,
    searchVectors: 0,
    stale,
    requiredFiles: { nodes: fileFacts?.nodesExists ?? false, edges: fileFacts?.edgesExists ?? false, manifest: manifest !== null },
  };
}
